import Link from "next/link";
type Stay={id:number;reference:string;guest_name:string;room_code:string|null;check_in:string;check_out:string;status:string;balance_cents:number};
type Room={id:number;code:string;room_type:string;operational_status:string;guest_name:string|null;booking_id:number|null;balance_cents:number|null};
type Service={id:number;name:string;price_cents:number;pricing_mode:string};
type Task={id:number;room_code:string;status:string;task_type:string;assigned_to:string|null};
export function FrontDeskPanels({arrivals,departures,rooms,balances,services,tasks,holds,paymentsToday,showFinancial}:{arrivals:Stay[];departures:Stay[];rooms:Room[];balances:Stay[];services:Service[];tasks:Task[];holds:number;paymentsToday:number;showFinancial:boolean}){
 const money=(v:number)=>new Intl.NumberFormat("el-GR",{style:"currency",currency:"EUR"}).format(Number(v)/100);
 const occupied=rooms.filter(r=>r.booking_id!==null).length;
 const unavailable=rooms.filter(r=>r.operational_status==="out_of_order"&&r.booking_id===null).length;
 return <section className="frontDesk"><div className="frontDeskHeading"><h2>Front desk · σήμερα</h2><p>Κατάσταση δωματίων, επισκεπτών και εργασιών του Hotel Corali.</p></div><div className="deskSummary"><div><small>Κατειλημμένα</small><strong>{occupied}</strong></div><div><small>Κενά προς διάθεση</small><strong>{rooms.length-occupied-unavailable}</strong></div><div><small>Εκτός λειτουργίας</small><strong>{unavailable}</strong></div><div><small>Ανοιχτές εργασίες</small><strong>{tasks.length}</strong></div>{showFinancial&&<div><small>Καθαρές εισπράξεις σήμερα</small><strong>{money(paymentsToday)}</strong></div>}</div><div className="frontDeskColumns"><article><h3>Αφίξεις σήμερα · {arrivals.length}</h3>{arrivals.length?arrivals.map(b=><Link className="deskRow" key={b.id} href={`/pms/reservations/${b.id}`}><strong>{b.guest_name}</strong><small>{b.reference} · {b.room_code??"Χωρίς δωμάτιο"}</small><span>{b.status}</span></Link>):<p>Δεν υπάρχουν αφίξεις.</p>}</article><article><h3>Αναχωρήσεις σήμερα · {departures.length}</h3>{departures.length?departures.map(b=><Link className="deskRow" key={b.id} href={`/pms/reservations/${b.id}`}><strong>{b.guest_name}</strong><small>{b.reference} · {b.room_code??"Χωρίς δωμάτιο"}</small>{showFinancial&&Number(b.balance_cents)>0&&<span>Υπόλοιπο {money(b.balance_cents)}</span>}</Link>):<p>Δεν υπάρχουν αναχωρήσεις.</p>}</article></div><div className="frontDeskColumns"><article><h3>{rooms.length} ενεργά δωμάτια · κατάσταση τώρα</h3><div className="deskRooms">{rooms.map(r=><Link key={r.id} href={r.booking_id?`/pms/reservations/${r.booking_id}`:"/pms/rooms"} className={`deskRoom ${r.operational_status}`}><strong>{r.code}</strong><small>{r.room_type}</small><span>{r.guest_name??r.operational_status}</span></Link>)}</div></article><article><h3>Εργασίες housekeeping · {tasks.length}</h3>{tasks.slice(0,12).map(t=><Link className="deskRow" href="/pms/housekeeping" key={t.id}><strong>{t.room_code} · {t.task_type}</strong><span>{t.status} · {t.assigned_to??"Χωρίς ανάθεση"}</span></Link>)}{!tasks.length&&<p>Δεν υπάρχουν ανοικτές εργασίες.</p>}<p>Προσωρινές δεσμεύσεις πληρωμής: <strong>{holds}</strong></p></article></div><div className="frontDeskColumns">{showFinancial&&<article><h3>Ανεξόφλητες κρατήσεις · {balances.length}{balances.length===50?"+":""}</h3>{balances.slice(0,12).map(b=><Link className="deskRow" href={`/pms/reservations/${b.id}`} key={b.id}><strong>{b.guest_name}</strong><small>{b.reference} · {b.check_in} → {b.check_out}</small><span>{money(b.balance_cents)}</span></Link>)}{!balances.length&&<p>Δεν υπάρχουν ανεξόφλητες ενεργές κρατήσεις.</p>}</article>}<article><h3>Διαθέσιμα extras · {services.length}</h3>{services.map(x=><Link className="deskRow" href="/pms/rooms/catalog" key={x.id}><strong>{x.name}</strong><span>{money(x.price_cents)} · {x.pricing_mode}</span></Link>)}{!services.length&&<p>Δεν υπάρχουν ενεργά extras.</p>}</article></div></section>
}
