import { requireUser } from "@/lib/auth";
import {db} from "@/lib/db";
import {can} from "@/lib/security/permissions";
import {Dashboard} from "./dashboard";
import {FrontDeskPanels} from "./front-desk-panels";
import {DashboardRefresh} from "./dashboard-refresh";

export default async function PmsPage() {
  const user = await requireUser("dashboard.read");
  const failures:string[]=[];
  const query=(sql:string,values:unknown[])=>db().query(sql,values).catch(error=>{const tag=sql.slice(0,90).replaceAll(/\s+/g," ");console.error("PMS dashboard query failed",tag,error);failures.push(tag);return {rows:[]}});
  const [notes,messages,arrivals,counts,bookings,forecast,recent,calendar]=await Promise.all([query(`SELECT id,body FROM pms_dashboard_notes WHERE owner_id=$1 ORDER BY updated_at DESC LIMIT 30`,[user.ownerId]),query(`SELECT 'message-'||m.id AS key,'Νέο μήνυμα κράτησης '||b.reference AS title,m.created_at FROM booking_messages m JOIN bookings b ON b.id=m.booking_id AND b.owner_id=m.owner_id LEFT JOIN pms_notification_reads r ON r.owner_id=m.owner_id AND r.notification_key='message-'||m.id WHERE m.owner_id=$1 AND m.sender='guest' AND r.notification_key IS NULL ORDER BY m.created_at DESC LIMIT 20`,[user.ownerId]),query(`SELECT 'arrival-'||id AS key,'Άφιξη σήμερα: '||guest_name AS title,created_at FROM bookings b LEFT JOIN pms_notification_reads r ON r.owner_id=b.owner_id AND r.notification_key='arrival-'||b.id WHERE b.owner_id=$1 AND b.check_in=(now() AT TIME ZONE 'Europe/Athens')::date::text AND b.status='confirmed' AND r.notification_key IS NULL`,[user.ownerId]),query(`SELECT
 (SELECT count(*) FROM bookings WHERE owner_id=$1 AND check_in=(now() AT TIME ZONE 'Europe/Athens')::date::text AND status IN ('confirmed','checked_in')) AS arrivals_today,
 (SELECT count(*) FROM bookings WHERE owner_id=$1 AND check_out=(now() AT TIME ZONE 'Europe/Athens')::date::text AND status IN ('confirmed','checked_in','checked_out')) AS departures_today,
 (SELECT count(*) FROM bookings WHERE owner_id=$1 AND check_in=((now() AT TIME ZONE 'Europe/Athens')::date+1)::text AND status='confirmed') AS arrivals_tomorrow,
 (SELECT count(*) FROM bookings WHERE owner_id=$1 AND check_out=((now() AT TIME ZONE 'Europe/Athens')::date+1)::text AND status IN ('confirmed','checked_in')) AS departures_tomorrow,
 (SELECT count(DISTINCT room_id) FROM bookings WHERE owner_id=$1 AND check_in<=(now() AT TIME ZONE 'Europe/Athens')::date::text AND check_out>(now() AT TIME ZONE 'Europe/Athens')::date::text AND status IN ('confirmed','checked_in')) AS occupied,
 (SELECT count(*) FROM rooms WHERE owner_id=$1 AND active=1) AS total_rooms`,[user.ownerId]),query(`SELECT id,guest_name,check_in,check_out,status,reference FROM bookings WHERE owner_id=$1 AND check_in>=(now() AT TIME ZONE 'Europe/Athens')::date::text AND status IN ('confirmed','checked_in') ORDER BY check_in,created_at DESC LIMIT 10`,[user.ownerId]),query(`SELECT d.day::text AS day,count(DISTINCT b.room_id)::int AS occupied FROM generate_series((now() AT TIME ZONE 'Europe/Athens')::date,(now() AT TIME ZONE 'Europe/Athens')::date+6,interval '1 day') AS d(day) LEFT JOIN bookings b ON b.owner_id=$1 AND b.check_in::date<=d.day::date AND b.check_out::date>d.day::date AND b.status IN ('confirmed','checked_in') GROUP BY d.day ORDER BY d.day`,[user.ownerId]),query(`SELECT id,guest_name,check_in,check_out,status,reference FROM bookings WHERE owner_id=$1 ORDER BY created_at DESC,id DESC LIMIT 10`,[user.ownerId]),query(`SELECT d.day::text AS day, count(DISTINCT b.id) FILTER(WHERE b.check_in::date=d.day::date)::int AS arrivals, count(DISTINCT b.id) FILTER(WHERE b.check_out::date=d.day::date)::int AS departures, count(DISTINCT b.room_id) FILTER(WHERE b.check_in::date<=d.day::date AND b.check_out::date>d.day::date)::int AS occupied FROM generate_series((now() AT TIME ZONE 'Europe/Athens')::date,(now() AT TIME ZONE 'Europe/Athens')::date+13,interval '1 day') AS d(day) LEFT JOIN bookings b ON b.owner_id=$1 AND b.status IN ('confirmed','checked_in') AND b.check_in::date<=d.day::date AND b.check_out::date>=d.day::date GROUP BY d.day ORDER BY d.day`,[user.ownerId])]);
  const financial=can(user.role,"folios.read",user.permissions);
  const [todayArrivals,todayDepartures,roomState,outstanding,services,tasks,holds,paymentsToday]=await Promise.all([
    query(`SELECT b.id,b.reference,b.guest_name,r.code room_code,b.check_in,b.check_out,b.status,b.balance_cents FROM bookings b LEFT JOIN rooms r ON r.id=b.room_id AND r.owner_id=b.owner_id WHERE b.owner_id=$1 AND b.check_in=(now() AT TIME ZONE 'Europe/Athens')::date::text AND b.status IN ('confirmed','checked_in') ORDER BY r.code,b.guest_name`,[user.ownerId]),
    query(`SELECT b.id,b.reference,b.guest_name,r.code room_code,b.check_in,b.check_out,b.status,b.balance_cents FROM bookings b LEFT JOIN rooms r ON r.id=b.room_id AND r.owner_id=b.owner_id WHERE b.owner_id=$1 AND b.check_out=(now() AT TIME ZONE 'Europe/Athens')::date::text AND b.status IN ('confirmed','checked_in','checked_out') ORDER BY r.code,b.guest_name`,[user.ownerId]),
    query(`SELECT r.id,r.code,r.room_type,r.operational_status,b.guest_name,b.id booking_id,b.balance_cents FROM rooms r LEFT JOIN LATERAL (SELECT id,guest_name,balance_cents FROM bookings b WHERE b.owner_id=r.owner_id AND b.room_id=r.id AND b.status IN ('confirmed','checked_in') AND b.check_in<=(now() AT TIME ZONE 'Europe/Athens')::date::text AND b.check_out>(now() AT TIME ZONE 'Europe/Athens')::date::text ORDER BY b.id DESC LIMIT 1) b ON true WHERE r.owner_id=$1 AND r.active=1 ORDER BY r.code`,[user.ownerId]),
    financial?query(`SELECT id,reference,guest_name,check_in,check_out,status,balance_cents FROM bookings WHERE owner_id=$1 AND status IN ('confirmed','checked_in') AND balance_cents>0 ORDER BY check_out LIMIT 50`,[user.ownerId]):Promise.resolve({rows:[]}),
    query(`SELECT id,name_el,name,price_cents,pricing_mode FROM extras WHERE owner_id=$1 AND active=1 ORDER BY sort_order,id LIMIT 30`,[user.ownerId]),
    query(`SELECT t.id,r.code room_code,t.status,t.task_type,t.assigned_to FROM housekeeping_tasks t JOIN rooms r ON r.id=t.room_id AND r.owner_id=t.owner_id WHERE t.owner_id=$1 AND t.status NOT IN ('ready','completed') ORDER BY t.id DESC LIMIT 30`,[user.ownerId]),
    query(`SELECT count(*)::int AS total FROM booking_sessions WHERE owner_id=$1 AND status='payment_pending' AND recovery_due_at>(extract(epoch from now())*1000)::bigint`,[user.ownerId]),
    financial?query(`SELECT COALESCE(sum(CASE WHEN entry_type IN ('payment','refund') THEN -amount_cents ELSE 0 END),0)::bigint AS net_cents FROM folio_entries WHERE owner_id=$1 AND created_at>=(extract(epoch from ((now() AT TIME ZONE 'Europe/Athens')::date AT TIME ZONE 'Europe/Athens'))*1000)::bigint AND created_at<(extract(epoch from (((now() AT TIME ZONE 'Europe/Athens')::date+1) AT TIME ZONE 'Europe/Athens'))*1000)::bigint`,[user.ownerId]):Promise.resolve({rows:[{net_cents:0}]})
  ]);
  return <section><p className="eyebrow">HOTEL CORALI · PISO LIVADI</p><h1>Επισκόπηση</h1><p>Καλώς ήρθατε, {user.displayName}.</p><DashboardRefresh/>{failures.length>0&&<p role="alert" className="notice">Ορισμένα στοιχεία της επισκόπησης δεν φορτώθηκαν. <a href="/api/pms/diagnostics" target="_blank" rel="noopener noreferrer">Έλεγχος βάσης PMS</a></p>}<Dashboard canCreateReservation={can(user.role,"reservations.create",user.permissions)} canEditNotes={can(user.role,"dashboard.write",user.permissions)} initialNotes={notes.rows} initialNotifications={[...messages.rows,...arrivals.rows]} bookings={bookings.rows} recent={recent.rows} calendar={calendar.rows.map(row=>({day:String(row.day).slice(0,10),arrivals:Number(row.arrivals),departures:Number(row.departures),occupied:Number(row.occupied)}))} forecast={forecast.rows.map(row=>({day:String(row.day).slice(0,10),occupied:Number(row.occupied)}))} counts={{arrivalsToday:Number(counts.rows[0]?.arrivals_today??0),departuresToday:Number(counts.rows[0]?.departures_today??0),arrivalsTomorrow:Number(counts.rows[0]?.arrivals_tomorrow??0),departuresTomorrow:Number(counts.rows[0]?.departures_tomorrow??0),occupied:Number(counts.rows[0]?.occupied??0),totalRooms:Number(counts.rows[0]?.total_rooms??0)}}/><FrontDeskPanels arrivals={todayArrivals.rows} departures={todayDepartures.rows} rooms={roomState.rows} balances={outstanding.rows} services={services.rows.map(row=>({...row,name:String(row.name_el||row.name)}))} tasks={tasks.rows} holds={Number(holds.rows[0]?.total??0)} paymentsToday={Number(paymentsToday.rows[0]?.net_cents??0)} showFinancial={financial}/></section>;
}
