"use client";
import {useEffect,useState} from "react";
import {bookingLanguage,bookingLocale,type BookingLanguage} from "@/lib/booking-i18n";
const texts={
 en:{title:"Pay reservation balance",success:"Your payment was submitted. The provider will confirm it shortly.",booking:"Reservation",balance:"Current balance",button:"Pay securely with Stripe",invalid:"This link is no longer active.",load:"Could not load the balance.",pay:"Payment could not start. Please contact the hotel."},
 el:{title:"Εξόφληση κράτησης",success:"Η πληρωμή υποβλήθηκε. Θα επιβεβαιωθεί σύντομα από τον πάροχο.",booking:"Κράτηση",balance:"Τρέχον υπόλοιπο",button:"Ασφαλής πληρωμή με Stripe",invalid:"Ο σύνδεσμος δεν είναι πλέον ενεργός.",load:"Η φόρτωση απέτυχε.",pay:"Η πληρωμή δεν ξεκίνησε. Επικοινωνήστε με το ξενοδοχείο."},
 fr:{title:"Régler le solde",success:"Votre paiement a été soumis et sera bientôt confirmé.",booking:"Réservation",balance:"Solde actuel",button:"Payer en sécurité avec Stripe",invalid:"Ce lien n’est plus actif.",load:"Impossible de charger le solde.",pay:"Paiement impossible. Contactez l’hôtel."},
 de:{title:"Restbetrag bezahlen",success:"Ihre Zahlung wurde eingereicht und wird bald bestätigt.",booking:"Buchung",balance:"Aktueller Restbetrag",button:"Sicher mit Stripe bezahlen",invalid:"Dieser Link ist nicht mehr aktiv.",load:"Restbetrag konnte nicht geladen werden.",pay:"Zahlung konnte nicht gestartet werden. Kontaktieren Sie das Hotel."},
 it:{title:"Paga il saldo",success:"Il pagamento è stato inviato e sarà confermato a breve.",booking:"Prenotazione",balance:"Saldo attuale",button:"Paga in sicurezza con Stripe",invalid:"Il link non è più attivo.",load:"Impossibile caricare il saldo.",pay:"Pagamento non riuscito. Contatta l’hotel."},
 es:{title:"Pagar el saldo",success:"Tu pago se ha enviado y se confirmará en breve.",booking:"Reserva",balance:"Saldo actual",button:"Paga de forma segura con Stripe",invalid:"Este enlace ya no está activo.",load:"No se pudo cargar el saldo.",pay:"No se pudo iniciar el pago. Ponte en contacto con el hotel."}
} as const;
export function PaymentBalance({token,status,initialLanguage}:{token:string;status:string;initialLanguage:string}){const [lang,setLang]=useState<BookingLanguage>(bookingLanguage(initialLanguage)),[balance,setBalance]=useState<number|null>(null),[reference,setReference]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),t=texts[lang];useEffect(()=>{if(!token)return;let alive=true;fetch(`/api/public/pay-balance?token=${encodeURIComponent(token)}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!alive)return;if(r.ok){setBalance(j.balanceCents);setReference(j.reference)}else setError(t.invalid)}).catch(()=>{if(alive)setError(t.load)});return()=>{alive=false}},[token,t.invalid,t.load]);async function pay(){setBusy(true);try{const r=await fetch("/api/public/pay-balance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})}),j=await r.json();if(!r.ok||!j.url)throw Error();location.assign(j.url)}catch{setError(t.pay);setBusy(false)}}return <main className="shell"><section className="card"><select aria-label="Language" value={lang} onChange={e=>setLang(bookingLanguage(e.target.value))}><option value="el">Ελληνικά</option><option value="en">English</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="it">Italiano</option><option value="es">Español</option></select><h1>{t.title}</h1>{status==="success"?<p>{t.success}</p>:<>{reference&&<p>{t.booking}: {reference}</p>}{balance!==null&&<><p>{t.balance}: <strong>{new Intl.NumberFormat(bookingLocale[lang],{style:"currency",currency:"EUR"}).format(balance/100)}</strong></p>{balance>0&&<button type="button" disabled={busy} onClick={pay}>{t.button}</button>}</>}{error&&<p role="alert" className="error">{error}</p>}</>}</section></main>}
