"use client";
import Image from "next/image";
import {useCallback,useEffect,useState} from "react";
import {bookingLanguage,bookingLocale,type BookingLanguage} from "@/lib/booking-i18n";
import {flag,languageCountry} from "@/lib/dial-codes";
import {guestLanguages,guestText} from "@/lib/guest-i18n";
type Policy={nonRefundable:boolean;deadline:string;freeCancellation:boolean;canCancel:boolean;refundCents:number;paidCents:number;canChangeDates:boolean;blocked:null|string};
type Data={policy:Policy;booking:{reference:string;guest_name:string;check_in:string;check_out:string;status:string;room_code:string;room_type:string;total_cents:number;balance_cents:number};messages:Array<{id:number;sender:string;body:string;created_at:number}>};
type Quote={nights:number;newTotalCents:number;differenceCents:number;newBalanceCents:number;refundDueCents:number;lastMinute:boolean};
const logo=<a className="guestLogo" href="https://hotelcorali.gr" aria-label="Hotel Corali"><Image src="/hotel-corali-logo.png" alt="Hotel Corali · Piso Livadi, Paros" width={602} height={151} priority/></a>;

export function ManageBooking({token:initialToken}:{token:string}){
 const[token,setToken]=useState(initialToken),[data,setData]=useState<Data|null>(null),[error,setError]=useState(false),[lang,setLang]=useState<BookingLanguage>("en"),[busy,setBusy]=useState(false),[messageError,setMessageError]=useState(false),t=guestText[lang];
 const[login,setLogin]=useState({reference:"",email:""}),[loginError,setLoginError]=useState("");
 const[change,setChange]=useState<{checkIn:string;checkOut:string}|null>(null),[quote,setQuote]=useState<Quote|null>(null),[notice,setNotice]=useState(""),[payUrl,setPayUrl]=useState<string|null>(null),[confirmCancel,setConfirmCancel]=useState(false);
 useEffect(()=>{queueMicrotask(()=>{const p=new URLSearchParams(location.search);setLang(bookingLanguage(p.get("lang")??navigator.language));const ref=p.get("ref");if(ref)setLogin(l=>({...l,reference:ref}))})},[]);
 const load=useCallback(async()=>{try{const r=await fetch(`/api/public/manage-booking?token=${encodeURIComponent(token)}&lang=${lang}`,{cache:"no-store"}),d=await r.json();if(r.ok){setData(d);setError(false)}else setError(true)}catch{setError(true)}},[token,lang]);
 useEffect(()=>{if(token){const id=setTimeout(load,0);return()=>clearTimeout(id)}},[token,load]);
 const money=(c:number)=>new Intl.NumberFormat(bookingLocale[lang],{style:"currency",currency:"EUR"}).format(Number(c)/100);
 const format=(v:string)=>new Intl.DateTimeFormat(bookingLocale[lang],{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}T12:00:00Z`));
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setLoginError("");try{const r=await fetch("/api/public/manage-booking/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)});const d=await r.json().catch(()=>({}));if(r.ok&&d.token){setToken(d.token);history.replaceState(null,"",`/manage-booking?token=${encodeURIComponent(d.token)}&lang=${lang}`)}else setLoginError(r.status===429?t.tooMany:t.loginFailed)}catch{setLoginError(t.loginFailed)}finally{setBusy(false)}}
 async function send(f:FormData){setBusy(true);try{const r=await fetch("/api/public/manage-booking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,body:f.get("body")})});if(r.ok){setMessageError(false);await load()}else setMessageError(true)}catch{setMessageError(true)}finally{setBusy(false)}}
 const errorText=(code?:string)=>code==="UNAVAILABLE"?t.unavailable:code==="PRICE_CHANGED"?t.priceChanged:t.changeError;
 async function checkPrice(){if(!change)return;setBusy(true);setNotice("");setQuote(null);try{const r=await fetch("/api/public/manage-booking/change",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,...change,lang})});const d=await r.json().catch(()=>({}));if(r.ok)setQuote(d.quote);else setNotice(errorText(d.error))}finally{setBusy(false)}}
 async function applyChange(){if(!change||!quote)return;setBusy(true);setNotice("");try{const r=await fetch("/api/public/manage-booking/change",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,...change,lang,confirm:true,expectedTotalCents:quote.newTotalCents})});const d=await r.json().catch(()=>({}));if(r.ok){setNotice(`${t.changed}${d.refundDueCents>0?` ${t.refundDue.replace("{amount}",money(d.refundDueCents))}`:""}`);setPayUrl(d.payUrl);setChange(null);setQuote(null);await load()}else{setNotice(errorText(d.error));if(d.error==="PRICE_CHANGED")setQuote(null)}}finally{setBusy(false)}}
 async function cancel(){setBusy(true);setNotice("");try{const r=await fetch("/api/public/manage-booking/cancel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,confirm:true})});const d=await r.json().catch(()=>({}));if(r.ok){setNotice(`${t.cancelDone}${d.refundCents>0?` ${t.refundDue.replace("{amount}",money(d.refundCents))}`:""}`);setConfirmCancel(false);await load()}else setNotice(t.changeError)}finally{setBusy(false)}}
 const picker=<label className="languagePicker"><span className="sr-only">Language</span><select aria-label="Language" value={lang} onChange={e=>setLang(bookingLanguage(e.target.value))}>{guestLanguages.map(x=><option value={x.code} key={x.code}>{flag(languageCountry[x.code])} {x.name}</option>)}</select></label>;
 const signOut=<button type="button" className="linkButton" onClick={()=>{setToken("");setData(null);setError(false);history.replaceState(null,"",`/manage-booking?lang=${lang}`)}}>{t.otherBooking}</button>;
 if(!token||error)return <main className="shell"><form className="card loginForm manageLogin" onSubmit={signIn}>{logo}{picker}<h1>{t.manage}</h1>{error&&<p className="error">{t.invalidLink}</p>}<p>{t.loginIntro}</p><label>{t.bookingNumber}<input value={login.reference} onChange={e=>setLogin({...login,reference:e.target.value})} required minLength={3} maxLength={40} autoComplete="off"/></label><label>{t.emailLabel}<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required maxLength={200} autoComplete="email"/></label>{loginError&&<p className="error" role="alert">{loginError}</p>}<button className="primary" disabled={busy}>{t.signIn}</button></form></main>;
 if(!data)return <main className="shell">{picker}<p>{t.loading}</p></main>;
 const b=data.booking,p=data.policy,today=new Date().toISOString().slice(0,10);
 const addDays=(d:string,n:number)=>new Date(Date.parse(`${d}T00:00:00Z`)+n*86400000).toISOString().slice(0,10);
 return <main className="shell"><section className="card manageCard">{logo}{picker}<h1>{t.yourBooking}</h1><p><b>{b.reference}</b> · {b.guest_name}</p><dl><dt>{t.room}</dt><dd>{b.room_code} · {b.room_type}</dd><dt>{t.in}</dt><dd>{format(b.check_in)}</dd><dt>{t.out}</dt><dd>{format(b.check_out)}</dd><dt>{t.status}</dt><dd>{t[b.status]??b.status}</dd><dt>{t.balance}</dt><dd>{money(b.balance_cents)}</dd></dl>
  {notice&&<p className="notice" role="status">{notice}</p>}
  {payUrl&&Number(b.balance_cents)>0&&<p><a className="primary payLink" href={payUrl}>{t.payNow} · {money(b.balance_cents)}</a></p>}
  {!p.blocked&&<section className="selfService"><h2>{t.selfServiceTitle}</h2>
   {p.nonRefundable&&<p className="hint">{t.nonRefundableNote}</p>}
   {p.canChangeDates?<div className="changeDates"><h3>{t.changeDates}</h3>{!change?<button type="button" className="secondaryButton" onClick={()=>{setChange({checkIn:b.check_in,checkOut:b.check_out});setNotice("")}}>{t.changeDates}</button>:<><div className="two"><label>{t.newCheckIn}<input type="date" min={today} value={change.checkIn} onChange={e=>{const v=e.target.value;setChange({checkIn:v,checkOut:change.checkOut>v?change.checkOut:addDays(v,1)});setQuote(null)}}/></label><label>{t.newCheckOut}<input type="date" min={addDays(change.checkIn,1)} value={change.checkOut} onChange={e=>{setChange({...change,checkOut:e.target.value});setQuote(null)}}/></label></div>
     {!quote?<div className="actions"><button type="button" className="primary" disabled={busy||change.checkOut<=change.checkIn}onClick={checkPrice}>{t.checkPrice}</button><button type="button" className="linkButton" onClick={()=>{setChange(null);setQuote(null)}}>✕</button></div>:<div className="quoteBox"><p><b>{t.newTotal}: {money(quote.newTotalCents)}</b><br/>{t.priceDifference}: {quote.differenceCents>=0?"+":""}{money(quote.differenceCents)}{quote.refundDueCents>0&&<><br/>{t.refundDue.replace("{amount}",money(quote.refundDueCents))}</>}{quote.newBalanceCents>0&&<><br/>{t.balance}: {money(quote.newBalanceCents)}{quote.lastMinute?` · ${t.payRequired}`:""}</>}</p><div className="actions"><button type="button" className="primary" disabled={busy} onClick={applyChange}>{t.confirmChange}</button><button type="button" className="linkButton" onClick={()=>setQuote(null)}>✕</button></div></div>}</>}</div>
   :!p.nonRefundable&&<p className="hint">{t.changeNotAllowed.replace("{date}",format(p.deadline))}</p>}
   {p.canCancel&&<div className="cancelBox"><h3>{t.cancelTitle}</h3><p>{p.freeCancellation?t.cancelFree.replace("{date}",format(p.deadline)).replace("{amount}",money(p.refundCents)):t.cancelNoRefund.replace("{amount}",money(p.paidCents))}</p>{!confirmCancel?<button type="button" className="secondaryButton danger" onClick={()=>setConfirmCancel(true)}>{t.cancelTitle}</button>:<div className="actions"><span>{t.cancelSure}</span><button type="button" className="danger" disabled={busy} onClick={cancel}>{t.cancelConfirm}</button><button type="button" className="linkButton" onClick={()=>setConfirmCancel(false)}>✕</button></div>}</div>}
  </section>}
  <h2>{t.messages}</h2><div className="thread">{data.messages.map(m=><div className={`bubble ${m.sender}`} key={m.id}><b>{m.sender==="guest"?t.you:"Hotel Corali"}</b><p>{m.body}</p></div>)}</div>{messageError&&<p role="alert" className="error">{t.messageError}</p>}<form action={send} className="messageComposer"><textarea name="body" required maxLength={4000} placeholder={t.write}/><button disabled={busy}>{t.send}</button></form>
  <p>{signOut}</p></section></main>
}
