import Stripe from "stripe";import {pushNotification} from "@/lib/pms-notifications";import {fulfillBookingSession} from "@/lib/booking-fulfillment";import {env} from "@/lib/env";import {withTransaction} from "@/lib/db";import {assertBalanceCheckout} from "@/lib/balance-payment";import {stripeCredentials} from "@/lib/provider-connections";import {assertStripeCheckoutMatches,stripeCheckoutIsPaid} from "@/lib/stripe-fulfillment";import {checkoutSecured} from "@/lib/stripe-options";
export async function POST(request:Request){const c=env(),credentials=await stripeCredentials(c.PMS_OWNER_ID);if(!credentials?.secretKey||!credentials.webhookSecret)return Response.json({ok:false,error:"NOT_CONFIGURED"},{status:503});const signature=request.headers.get("stripe-signature");if(!signature)return Response.json({ok:false,error:"MISSING_SIGNATURE"},{status:400});const stripe=new Stripe(credentials.secretKey);let event:Stripe.Event;try{event=stripe.webhooks.constructEvent(await request.text(),signature,credentials.webhookSecret)}catch{return Response.json({ok:false,error:"INVALID_SIGNATURE"},{status:400})}if(event.type!=="checkout.session.completed"&&event.type!=="checkout.session.async_payment_succeeded")return Response.json({ok:true,ignored:true});const session=event.data.object;if(session.metadata?.kind==="balance"){if(!stripeCheckoutIsPaid(session))return Response.json({ok:true,pending:true});
  const linkId=Number(session.metadata.balance_link_id),bookingId=Number(session.metadata.booking_id),amount=Number(session.amount_total);
  if(!Number.isSafeInteger(linkId)||!Number.isSafeInteger(bookingId)||!Number.isSafeInteger(amount)||session.currency?.toLowerCase()!=="eur")return Response.json({ok:false,error:"INVALID_BALANCE_METADATA"},{status:400});
  try{await withTransaction(async client=>{const l=await client.query(`SELECT * FROM balance_payment_links WHERE id=$1 AND owner_id=$2 FOR UPDATE`,[linkId,c.PMS_OWNER_ID]),link=l.rows[0];if(!link||Number(link.booking_id)!==bookingId||link.checkout_session_id!==session.id)throw Error("BALANCE_LINK_MISMATCH");if(link.status==="paid")return;const b=await client.query(`SELECT * FROM bookings WHERE id=$1 AND owner_id=$2 FOR UPDATE`,[bookingId,c.PMS_OWNER_ID]),booking=b.rows[0];if(!booking)throw Error("NOT_FOUND");assertBalanceCheckout(amount,Number(booking.balance_cents),link.status,String(session.metadata?.owner_id),c.PMS_OWNER_ID);if(Number(link.amount_cents)!==amount||session.metadata?.amount_cents!==String(amount))throw Error("BALANCE_PAYMENT_MISMATCH");const now=Date.now(),reference=session.payment_intent?String(session.payment_intent):session.id;await client.query(`INSERT INTO payment_transactions(owner_id,booking_id,provider,provider_reference,kind,status,amount_cents,currency,created_at) VALUES($1,$2,'stripe',$3,'payment','succeeded',$4,'EUR',$5) ON CONFLICT(provider,provider_reference) DO NOTHING`,[c.PMS_OWNER_ID,bookingId,reference,amount,now]);await client.query(`INSERT INTO folio_entries(owner_id,booking_id,entry_type,description,amount_cents,payer,actor_id,created_at,payment_method,receipt_reference) VALUES($1,$2,'payment','Stripe balance payment',$3,'guest','stripe-webhook',$4,'stripe',$5) ON CONFLICT DO NOTHING`,[c.PMS_OWNER_ID,bookingId,-amount,now,reference]);await client.query(`UPDATE bookings SET balance_cents=0,version=version+1 WHERE owner_id=$1 AND id=$2`,[c.PMS_OWNER_ID,bookingId]);await client.query(`UPDATE balance_payment_links SET status='paid',paid_at=$1 WHERE id=$2`,[now,linkId]);await pushNotification(client,c.PMS_OWNER_ID,{kind:"payment",titleEl:`Πληρωμή υπολοίπου €${(amount/100).toFixed(2)} · ${booking.reference}`,titleEn:`Balance payment €${(amount/100).toFixed(2)} · ${booking.reference}`,link:`/pms/reservations/${bookingId}`});await client.query(`UPDATE balance_payment_links SET status='revoked' WHERE owner_id=$1 AND booking_id=$2 AND status='active'`,[c.PMS_OWNER_ID,bookingId]);});return Response.json({ok:true})}catch(e){console.error("balance fulfillment failed",e);return Response.json({ok:false,error:"BALANCE_FULFILLMENT_FAILED"},{status:409})}
 }const sessionId=Number(session.metadata?.booking_session_id);if(!Number.isSafeInteger(sessionId))return Response.json({ok:false,error:"MISSING_METADATA"},{status:400});// Paid, held (manual capture) or card saved (setup mode): each secures the booking; anything else waits for a later event.
 const intent=session.payment_intent?await stripe.paymentIntents.retrieve(String(session.payment_intent)).catch(()=>null):null,setup=session.setup_intent?await stripe.setupIntents.retrieve(String(session.setup_intent)).catch(()=>null):null;
 const secured=checkoutSecured(session,intent?.status??null,setup?.status??null);if(!secured)return Response.json({ok:true,pending:true});
 try{await withTransaction(async client=>{const locked=await client.query(`SELECT * FROM booking_sessions WHERE id=$1 AND owner_id=$2 FOR UPDATE`,[sessionId,c.PMS_OWNER_ID]),source=locked.rows[0];if(!source)throw new Error("NOT_FOUND");if(source.status==="completed")return;assertStripeCheckoutMatches(session,source,secured);
  const customerRef=typeof session.customer==="string"?session.customer:intent&&typeof intent.customer==="string"?intent.customer:setup&&typeof setup.customer==="string"?setup.customer:null;
  const paymentMethodRef=setup&&typeof setup.payment_method==="string"?setup.payment_method:intent&&typeof intent.payment_method==="string"&&intent.setup_future_usage==="off_session"?intent.payment_method:null;
  const first=await fulfillBookingSession(client,c.PMS_OWNER_ID,source,{provider:"stripe",reference:secured==="card_saved"?String(setup!.id):session.payment_intent?String(session.payment_intent):session.id,amountCents:secured==="paid"?Number(session.amount_total):0,status:secured==="paid"?"succeeded":secured,authorizedCents:secured==="authorized"?Number(intent!.amount_capturable):0,customerRef,paymentMethodRef});
  if(secured==="authorized")await client.query(`UPDATE bookings SET stripe_authorization_ref=$1,stripe_authorized_cents=$2,stripe_authorized_at=$3 WHERE owner_id=$4 AND id=$5`,[String(intent!.id),Number(intent!.amount_capturable),Date.now(),c.PMS_OWNER_ID,first]);
 });return Response.json({ok:true})}catch(e){console.error("stripe fulfillment failed",e);return Response.json({ok:false,error:e instanceof Error&&e.message==="ROOM_UNAVAILABLE"?"ROOM_UNAVAILABLE":"FULFILLMENT_FAILED"},{status:409})}}
