"use client";
import {useRouter} from "next/navigation";
import {useState} from "react";
type Row=Record<string,string|number|null>;
const numbers=(v:FormDataEntryValue|null)=>String(v??"").replaceAll(/[[\]"\s]/g,"").split(",").filter(Boolean).map(Number).filter(x=>Number.isInteger(x)&&x>=0&&x<=6);
const strings=(v:FormDataEntryValue|null)=>String(v??"").replaceAll(/[\[\]"]/g,"").split(",").map(x=>x.trim()).filter(Boolean);
export function RulesManager({specials,restrictions,canCreate,canEdit}:{specials:Row[];restrictions:Row[];canCreate:boolean;canEdit:boolean}){const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),router=useRouter();async function save(body:object){setBusy(true);try{const r=await fetch("/api/pms/rules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error);setMsg("Αποθηκεύτηκε.");router.refresh()}catch(e){setMsg(`Αποτυχία αποθήκευσης: ${e instanceof Error?e.message:"άγνωστο"}`)}finally{setBusy(false)}}
 const special=(f:FormData,id?:number)=>({kind:"special",...(id?{id}:{}),name:f.get("name"),startsOn:f.get("start"),endsOn:f.get("end"),adjustmentType:f.get("type"),adjustmentValue:f.get("type")==="fixed"?Math.round(Number(f.get("value"))*100):Number(f.get("value")),operation:f.get("operation"),minimumStay:Number(f.get("min")),weekdays:numbers(f.get("weekdays")),roomCodes:strings(f.get("rooms")),ratePlanKeys:strings(f.get("plans")),active:f.get("active")==="on"});
 const restriction=(f:FormData,id?:number)=>({kind:"restriction",...(id?{id}:{}),name:f.get("name"),startsOn:f.get("start"),endsOn:f.get("end"),minimumStay:Number(f.get("min")),maximumStay:f.get("max")?Number(f.get("max")):null,closedArrivalWeekdays:numbers(f.get("arrivals")),closedDepartureWeekdays:numbers(f.get("departures")),roomCodes:strings(f.get("rooms")),ratePlanKeys:strings(f.get("plans")),active:f.get("active")==="on"});
 function fields(x:Row|null,kind:"special"|"restriction"){return <><input name="name" placeholder="Όνομα" defaultValue={x?.name??""} required/><input name="start" aria-label="Από" type="date" defaultValue={x?.starts_on??""} required/><input name="end" aria-label="Έως" type="date" defaultValue={x?.ends_on??""} required/>{kind==="special"&&<><select name="operation" defaultValue={x?.operation??"discount"}><option value="discount">Έκπτωση</option><option value="charge">Προσαύξηση</option></select><select name="type" defaultValue={x?.adjustment_type??"percentage"}><option value="percentage">Ποσοστό %</option><option value="fixed">Σταθερό ποσό €</option></select><input name="value" aria-label="Ποσό / ποσοστό" type="number" min="0" step="0.01" defaultValue={x?.adjustment_type==="fixed"?Number(x.adjustment_value)/100:x?.adjustment_value??0} required/><input name="weekdays" placeholder="Ημέρες 0=Κυριακή, 1=Δευτέρα..." defaultValue={x?.weekdays??""}/></>}<input name="min" aria-label="Ελάχιστες νύχτες" type="number" min="1" defaultValue={x?.minimum_stay??1} required/>{kind==="restriction"&&<><input name="max" aria-label="Μέγιστες νύχτες" type="number" min="1" defaultValue={x?.maximum_stay??""}/><input name="arrivals" placeholder="Κλειστή άφιξη: 0,1..." defaultValue={x?.closed_arrival_weekdays??""}/><input name="departures" placeholder="Κλειστή αναχώρηση: 0,1..." defaultValue={x?.closed_departure_weekdays??""}/></>}<input name="rooms" placeholder="Κωδικοί δωματίων χωρισμένοι με κόμμα" defaultValue={x?.room_codes??""}/><input name="plans" placeholder="Κωδικοί rate plans χωρισμένοι με κόμμα" defaultValue={x?.rate_plan_keys??""}/><label><input name="active" type="checkbox" defaultChecked={x?Boolean(Number(x.active)):true}/> Ενεργό</label></>}
 return <><p className="notice" role="status">{msg}</p><div className="pricingGrid"><article><h2>Special prices / προσφορές</h2>{specials.map(x=><form key={String(x.id)} action={f=>save(special(f,Number(x.id)))}>{fields(x,"special")}<button disabled={busy||!canEdit}>Αποθήκευση</button></form>)}{canCreate&&<form action={f=>save(special(f))}><h3>Νέα προσφορά</h3>{fields(null,"special")}<button disabled={busy}>Προσθήκη</button></form>}</article><article><h2>Περιορισμοί</h2>{restrictions.map(x=><form key={String(x.id)} action={f=>save(restriction(f,Number(x.id)))}>{fields(x,"restriction")}<button disabled={busy||!canEdit}>Αποθήκευση</button></form>)}{canCreate&&<form action={f=>save(restriction(f))}><h3>Νέος περιορισμός</h3>{fields(null,"restriction")}<button disabled={busy}>Προσθήκη</button></form>}</article></div></>}
