"use client";
import { useMemo,useState } from "react";
import {useRouter} from "next/navigation";

type Room={id:number;code:string;room_type:string;operational_status:string}; type Booking={id:number;reference:string;guest_name:string;room_id:number;check_in:string;check_out:string;status:string;version:number};
function datePlus(start:string,days:number){const d=new Date(`${start}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export function RoomGrid({start,days,rooms,initialBookings}:{start:string;days:number;rooms:Room[];initialBookings:Booking[]}){
 const router=useRouter();const [bookings,setBookings]=useState(initialBookings); const [message,setMessage]=useState(""),[menu,setMenu]=useState<Booking|null>(null); const dates=useMemo(()=>Array.from({length:days},(_,i)=>datePlus(start,i)),[start,days]);
 async function move(id:number,roomId:number,checkIn:string){const booking=bookings.find(b=>b.id===id);if(!booking)return;const nights=Math.max(1,(Date.parse(booking.check_out)-Date.parse(booking.check_in))/86400000);const checkOut=datePlus(checkIn,nights);const response=await fetch(`/api/pms/reservations/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"move",version:booking.version,roomId,checkIn,checkOut})});const data=await response.json();if(!response.ok){setMessage(data.error==="ROOM_UNAVAILABLE"?"Το δωμάτιο δεν είναι διαθέσιμο για αυτές τις ημερομηνίες.":"Η κράτηση άλλαξε από άλλο χρήστη. Ανανεώστε τη σελίδα.");return}setBookings(rows=>rows.map(row=>row.id===id?{...row,...data.booking}:row));setMessage("Η κράτηση μετακινήθηκε.")}
 async function quickAction(action:"check_in"|"check_out"){if(!menu)return;const r=await fetch(`/api/pms/reservations/${menu.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,version:menu.version})}),d=await r.json();if(r.ok){setBookings(v=>v.map(x=>x.id===menu.id?{...x,...d.booking}:x));setMessage("Η κατάσταση ενημερώθηκε.");setMenu(null)}else setMessage(d.error??"Η ενέργεια απέτυχε.")}
 return <><p className="notice" aria-live="polite">{message}</p><div className="tape"><div className="tapeHead"><b>Δωμάτιο</b>{dates.map(d=><span key={d}>{new Date(`${d}T00:00:00Z`).toLocaleDateString("el-GR",{day:"2-digit",month:"2-digit"})}</span>)}</div>{rooms.map(room=><div className="tapeRow" key={room.id}><b>{room.code}<small>{room.room_type}<br/>{room.operational_status}</small></b>{dates.map(date=>{const booking=bookings.find(b=>b.room_id===room.id&&b.check_in<=date&&b.check_out>date);return <div key={date} className="slot" onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData("bookingId")),room.id,date)} onDoubleClick={()=>{if(!booking)router.push(`/pms/reservations/new?roomId=${room.id}&checkIn=${date}`)}}>{booking&&booking.check_in===date?<button draggable onDragStart={e=>e.dataTransfer.setData("bookingId",String(booking.id))} onContextMenu={e=>{e.preventDefault();setMenu(booking)}} onClick={()=>setMenu(booking)} className={`bookingBar ${booking.status}`} title={`${booking.guest_name} · ${booking.check_in} → ${booking.check_out}`}>{booking.guest_name}</button>:null}</div>})}</div>)}</div>{menu&&<div className="quickMenu"><b>{menu.guest_name}</b><small>{menu.reference}</small>{menu.status==="confirmed"&&<button onClick={()=>quickAction("check_in")}>Check-in</button>}{menu.status==="checked_in"&&<button onClick={()=>quickAction("check_out")}>Check-out</button>}<button onClick={()=>router.push(`/pms/reservations/${menu.id}`)}>Folio / στοιχεία</button><button className="close" onClick={()=>setMenu(null)}>Κλείσιμο</button></div>}</>
}
