"use client";
import {useEffect,useState} from "react";
import {bookingLanguage,type BookingLanguage} from "@/lib/booking-i18n";
import {guestLanguages,guestText} from "@/lib/guest-i18n";
export function CheckinForm({token}:{token:string}){
 const [lang,setLang]=useState<BookingLanguage>("en"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),t=guestText[lang];
 useEffect(()=>{queueMicrotask(()=>setLang(bookingLanguage(new URLSearchParams(location.search).get("lang")??navigator.language)))},[]);
 async function submit(form:FormData){setBusy(true);try{const body=Object.fromEntries(form);const r=await fetch("/api/public/check-in",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,token,luggageAssistance:form.get("luggageAssistance")==="on",emailMarketingConsent:form.get("emailMarketingConsent")==="on",whatsappMarketingConsent:form.get("whatsappMarketingConsent")==="on"})});setMessage(r.ok?t.submitted:t.checkinError)}catch{setMessage(t.checkinError)}finally{setBusy(false)}}
 return <main className="shell"><form action={submit} className="card loginForm"><h1>{t.checkin}</h1><label>{t.language}<select value={lang} onChange={e=>setLang(bookingLanguage(e.target.value))}>{guestLanguages.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label><input type="hidden" name="preferredLanguage" value={lang}/><label>{t.first}<input name="firstName" required/></label><label>{t.last}<input name="lastName" required/></label><label>{t.email}<input name="email" type="email" required/></label><label>{t.phone}<input name="phone" type="tel" required/></label><label>{t.arrival}<input name="arrivalTime" type="time" required/></label><label>{t.documentType}<select name="documentType"><option value="passport">{t.passport}</option><option value="identity_card">{t.identity}</option></select></label><label>{t.documentNumber}<input name="documentNumber" required/></label><label>{t.dob}<input name="dateOfBirth" type="date" required/></label><label>{t.travel}<textarea name="travelDetails" maxLength={500}/></label><label>{t.requests}<textarea name="specialRequests" maxLength={1000}/></label><label><input type="checkbox" name="luggageAssistance"/> {t.luggage}</label><label><input type="checkbox" name="emailMarketingConsent"/> {t.emailConsent}</label><label><input type="checkbox" name="whatsappMarketingConsent"/> {t.whatsappConsent}</label><button disabled={!token||busy}>{t.submit}</button><p role="status">{message}</p></form></main>
}
