"use client";
import Image from "next/image";
import {useEffect,useMemo,useState} from "react";
import {countryCodes} from "@/lib/country-codes";
import {dialCodes,flag,internationalPhone,languageCountry} from "@/lib/dial-codes";
import {bookingLanguage,bookingLocale,bookingText,type BookingLanguage} from "@/lib/booking-i18n";
import {guestLanguages,guestText} from "@/lib/guest-i18n";
type Options={modes:{mode:string;hubs:{key:string;name:string}[];transfer:boolean}[];vehicles:{key:string;name:string;priceCents:number;maxPassengers:number}[]};
type Result={instructions:{hubName:string;text:string}|null;transfer:{vehicle:string;priceCents:number}|null};
type Prefill={booking:{reference:string;checkIn:string;checkOut:string;nights:number;adults:number;children:number;room:{type:string;names:Record<string,string>}};guest:{firstName:string;lastName:string;email:string;phoneCountry:string;phoneLocal:string;arrivalTime:string;travelDetails:string;specialRequests:string;luggageAssistance:boolean;submitted:boolean}};
export function CheckinForm({token}:{token:string}){
 const [lang,setLang]=useState<BookingLanguage>("en"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),t=guestText[lang];
 const [options,setOptions]=useState<Options|null>(null),[mode,setMode]=useState(""),[hub,setHub]=useState(""),[vehicle,setVehicle]=useState(""),[result,setResult]=useState<Result|null>(null);
 const [phoneCountry,setPhoneCountry]=useState("GR"),[mounted,setMounted]=useState(false);
 useEffect(()=>{queueMicrotask(()=>{const l=bookingLanguage(new URLSearchParams(location.search).get("lang")??navigator.language);setLang(l);setPhoneCountry(languageCountry[l]??"GR");setMounted(true)})},[]);
 const [prefill,setPrefill]=useState<Prefill|null>(null),[linkInvalid,setLinkInvalid]=useState(false);
 // Pre-fill from the booking behind this personal link (reference, stay, room and contact details).
 useEffect(()=>{if(!token)return;let live=true;fetch(`/api/public/check-in?token=${encodeURIComponent(token)}`,{cache:"no-store"}).then(async r=>{const d=await r.json().catch(()=>null);if(!live)return;if(r.status===401){setLinkInvalid(true);return}if(r.ok&&d?.ok){setPrefill(d);if(d.guest.phoneCountry)setPhoneCountry(d.guest.phoneCountry)}}).catch(()=>{});return()=>{live=false}},[token]);
 const g=prefill?.guest;
 const roomName=prefill?(prefill.booking.room.names[lang]||prefill.booking.room.names.en||prefill.booking.room.names.el||prefill.booking.room.type):"";
 const fmt=(d:string,o:Intl.DateTimeFormatOptions)=>new Date(`${d}T00:00:00Z`).toLocaleDateString(bookingLocale[lang],{...o,timeZone:"UTC"});
 const weekday=(d:string)=>fmt(d,{weekday:"long"}),year=(d:string)=>fmt(d,{year:"numeric"});
 // Day and month taken from one formatted date so the month has the right grammatical form (e.g. «29 Οκτωβρίου»).
 const dayParts=(d:string)=>{const parts=new Intl.DateTimeFormat(bookingLocale[lang],{day:"numeric",month:"long",timeZone:"UTC"}).formatToParts(new Date(`${d}T00:00:00Z`));return {day:parts.find(x=>x.type==="day")?.value??"",month:parts.find(x=>x.type==="month")?.value??""}};
 const dialOptions=useMemo(()=>{if(!mounted)return [{code:phoneCountry,name:""}];const display=new Intl.DisplayNames([bookingLocale[lang]],{type:"region"}),collator=new Intl.Collator(bookingLocale[lang]);return countryCodes.filter(code=>dialCodes[code]).map(code=>({code,name:display.of(code)??code})).sort((a,b)=>collator.compare(a.name,b.name))},[lang,mounted,phoneCountry]);
 useEffect(()=>{let live=true;fetch(`/api/public/arrival-options?lang=${lang}`).then(r=>r.ok?r.json():null).then(d=>{if(live&&d)setOptions(d)}).catch(()=>{});return()=>{live=false}},[lang]);
 const current=options?.modes.find(m=>m.mode===mode);
 const price=(cents:number)=>new Intl.NumberFormat(bookingLocale[lang],{style:"currency",currency:"EUR"}).format(cents/100);
 async function submit(form:FormData){setBusy(true);try{const {phoneCountry:country,phoneLocal,...body}=Object.fromEntries(form);const phone=internationalPhone(String(country??phoneCountry),String(phoneLocal??""));const r=await fetch("/api/public/check-in",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,phone,token,luggageAssistance:form.get("luggageAssistance")==="on",emailMarketingConsent:form.get("emailMarketingConsent")==="on",whatsappMarketingConsent:form.get("whatsappMarketingConsent")==="on",arrivalMode:mode||undefined,arrivalHub:mode?hub:undefined,transferVehicle:mode&&current?.transfer&&vehicle?vehicle:undefined})});const d=await r.json().catch(()=>({}));if(r.ok){setResult({instructions:d.instructions??null,transfer:d.transfer??null});setMessage(t.submitted)}else setMessage(d.error==="VEHICLE_TOO_SMALL"?t.vehicleTooSmall:t.checkinError)}catch{setMessage(t.checkinError)}finally{setBusy(false)}}
 if(result)return <main className="shell"><section className="card loginForm arrivalResult"><a className="guestLogo" href="https://hotelcorali.gr" aria-label="Hotel Corali"><Image src="/hotel-corali-logo.png" alt="Hotel Corali · Piso Livadi, Paros" width={602} height={151} priority/></a><h1>{t.checkin}</h1><p role="status">{message}</p>{result.transfer&&<p className="notice">{t.transferAdded.replace("{vehicle}",result.transfer.vehicle).replace("{price}",price(result.transfer.priceCents))}</p>}{result.instructions&&<><h2>{t.instructionsTitle}</h2><h3>{result.instructions.hubName}</h3><p className="arrivalText">{result.instructions.text}</p></>}</section></main>;
 return <main className="shell"><form key={prefill?"prefilled":"empty"} action={submit} className="card loginForm"><a className="guestLogo" href="https://hotelcorali.gr" aria-label="Hotel Corali"><Image src="/hotel-corali-logo.png" alt="Hotel Corali · Piso Livadi, Paros" width={602} height={151} priority/></a><h1>{t.checkin}</h1>{linkInvalid&&<p className="formError" role="alert">{t.invalidLink}</p>}{prefill&&<section className="checkinBooking" aria-label={t.yourBooking}>
   <header className="cbHead"><h2>{t.yourBooking}</h2><span className="cbRef"><small>{t.bookingRef}</small><b>{prefill.booking.reference}</b></span></header>
   <div className="cbDates">
    <div className="cbDate"><small>{t.in}</small><span className="cbWeekday">{weekday(prefill.booking.checkIn)}</span><b className="cbDay">{dayParts(prefill.booking.checkIn).day}</b><span className="cbMonth">{dayParts(prefill.booking.checkIn).month}</span><span className="cbYear">{year(prefill.booking.checkIn)}</span></div>
    <div className="cbNights" aria-label={t.nightsN.replace("{n}",String(prefill.booking.nights))}><span>🌙 {t.nightsN.replace("{n}",String(prefill.booking.nights))}</span><i aria-hidden="true"/></div>
    <div className="cbDate"><small>{t.out}</small><span className="cbWeekday">{weekday(prefill.booking.checkOut)}</span><b className="cbDay">{dayParts(prefill.booking.checkOut).day}</b><span className="cbMonth">{dayParts(prefill.booking.checkOut).month}</span><span className="cbYear">{year(prefill.booking.checkOut)}</span></div>
   </div>
   <ul className="cbFacts">
    {roomName&&<li><span aria-hidden="true">🛏️</span><small>{t.roomLabel}</small><b>{roomName}</b></li>}
    <li><span aria-hidden="true">👥</span><small>{t.guestsLabel}</small><b>{t.guestsN.replace("{a}",String(prefill.booking.adults))}{prefill.booking.children>0?` · ${t.childrenN.replace("{c}",String(prefill.booking.children))}`:""}</b></li>
   </ul>
   <p className="cbNote">{g?.submitted?"✅ "+t.alreadySubmitted:"ℹ️ "+t.prefillNote}</p>
  </section>}<label>{t.language}<select value={lang} onChange={e=>setLang(bookingLanguage(e.target.value))}>{guestLanguages.map(x=><option key={x.code} value={x.code}>{flag(languageCountry[x.code])} {x.name}</option>)}</select></label><input type="hidden" name="preferredLanguage" value={lang}/><label>{t.first}<input name="firstName" defaultValue={g?.firstName} required/></label><label>{t.last}<input name="lastName" defaultValue={g?.lastName} required/></label><label>{t.email}<input name="email" type="email" defaultValue={g?.email} required/></label><label>{t.phone}<span className="phoneField"><select name="phoneCountry" aria-label={bookingText[lang].phoneCountry} value={phoneCountry} onChange={e=>setPhoneCountry(e.target.value)}>{dialOptions.map(x=><option value={x.code} key={x.code}>{flag(x.code)} +{dialCodes[x.code]} · {x.name}</option>)}</select><input name="phoneLocal" type="tel" inputMode="tel" autoComplete="tel-national" defaultValue={g?.phoneLocal} required/></span></label><label>{t.arrival}<input name="arrivalTime" type="time" defaultValue={g?.arrivalTime} required/></label>
  {options&&options.modes.length>0&&<fieldset className="arrivalPick"><legend>{t.arrivalHow}</legend><select aria-label={t.arrivalHow} value={mode} onChange={e=>{const m=e.target.value;setMode(m);setHub(options.modes.find(x=>x.mode===m)?.hubs[0]?.key??"");setVehicle("")}}><option value="">{t.modeNone}</option>{options.modes.map(m=><option key={m.mode} value={m.mode}>{t[`mode_${m.mode}`]??m.mode}</option>)}</select>
   {current&&current.hubs.length>1&&<label>{t.hub}<select value={hub} onChange={e=>setHub(e.target.value)}>{current.hubs.map(h=><option key={h.key} value={h.key}>{h.name}</option>)}</select></label>}
   {current?.transfer&&options.vehicles.length>0&&<label>{t.transfer}<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">{t.transferNone}</option>{options.vehicles.map(v=><option key={v.key} value={v.key}>{v.name} · {price(v.priceCents)}</option>)}</select>{vehicle&&<small>{t.transferNote}</small>}</label>}
  </fieldset>}
  <label>{t.documentType}<select name="documentType"><option value="passport">{t.passport}</option><option value="identity_card">{t.identity}</option></select></label><label>{t.documentNumber}<input name="documentNumber" required/></label><label>{t.dob}<input name="dateOfBirth" type="date" required/></label><label>{t.travel}<textarea name="travelDetails" maxLength={500} defaultValue={g?.travelDetails}/></label><label>{t.requests}<textarea name="specialRequests" maxLength={1000} defaultValue={g?.specialRequests}/></label><label className="guestCheck"><input type="checkbox" name="luggageAssistance" defaultChecked={g?.luggageAssistance}/><span>{t.luggage}</span></label><label className="guestCheck"><input type="checkbox" name="emailMarketingConsent"/><span>{t.emailConsent}</span></label><label className="guestCheck"><input type="checkbox" name="whatsappMarketingConsent"/><span>{t.whatsappConsent}</span></label><button disabled={!token||busy}>{t.submit}</button><p role="status">{message}</p></form></main>}
