"use client";
import {useEffect,useState} from "react";
import {bookingLanguage,bookingLocale,type BookingLanguage} from "@/lib/booking-i18n";
import {guestLanguages,guestText} from "@/lib/guest-i18n";
type Options={modes:{mode:string;hubs:{key:string;name:string}[];transfer:boolean}[];vehicles:{key:string;name:string;priceCents:number;maxPassengers:number}[]};
type Result={instructions:{hubName:string;text:string}|null;transfer:{vehicle:string;priceCents:number}|null};
export function CheckinForm({token}:{token:string}){
 const [lang,setLang]=useState<BookingLanguage>("en"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),t=guestText[lang];
 const [options,setOptions]=useState<Options|null>(null),[mode,setMode]=useState(""),[hub,setHub]=useState(""),[vehicle,setVehicle]=useState(""),[result,setResult]=useState<Result|null>(null);
 useEffect(()=>{queueMicrotask(()=>setLang(bookingLanguage(new URLSearchParams(location.search).get("lang")??navigator.language)))},[]);
 useEffect(()=>{let live=true;fetch(`/api/public/arrival-options?lang=${lang}`).then(r=>r.ok?r.json():null).then(d=>{if(live&&d)setOptions(d)}).catch(()=>{});return()=>{live=false}},[lang]);
 const current=options?.modes.find(m=>m.mode===mode);
 const price=(cents:number)=>new Intl.NumberFormat(bookingLocale[lang],{style:"currency",currency:"EUR"}).format(cents/100);
 async function submit(form:FormData){setBusy(true);try{const body=Object.fromEntries(form);const r=await fetch("/api/public/check-in",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,token,luggageAssistance:form.get("luggageAssistance")==="on",emailMarketingConsent:form.get("emailMarketingConsent")==="on",whatsappMarketingConsent:form.get("whatsappMarketingConsent")==="on",arrivalMode:mode||undefined,arrivalHub:mode?hub:undefined,transferVehicle:mode&&current?.transfer&&vehicle?vehicle:undefined})});const d=await r.json().catch(()=>({}));if(r.ok){setResult({instructions:d.instructions??null,transfer:d.transfer??null});setMessage(t.submitted)}else setMessage(d.error==="VEHICLE_TOO_SMALL"?t.vehicleTooSmall:t.checkinError)}catch{setMessage(t.checkinError)}finally{setBusy(false)}}
 if(result)return <main className="shell"><section className="card loginForm arrivalResult"><h1>{t.checkin}</h1><p role="status">{message}</p>{result.transfer&&<p className="notice">{t.transferAdded.replace("{vehicle}",result.transfer.vehicle).replace("{price}",price(result.transfer.priceCents))}</p>}{result.instructions&&<><h2>{t.instructionsTitle}</h2><h3>{result.instructions.hubName}</h3><p className="arrivalText">{result.instructions.text}</p></>}</section></main>;
 return <main className="shell"><form action={submit} className="card loginForm"><h1>{t.checkin}</h1><label>{t.language}<select value={lang} onChange={e=>setLang(bookingLanguage(e.target.value))}>{guestLanguages.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label><input type="hidden" name="preferredLanguage" value={lang}/><label>{t.first}<input name="firstName" required/></label><label>{t.last}<input name="lastName" required/></label><label>{t.email}<input name="email" type="email" required/></label><label>{t.phone}<input name="phone" type="tel" required/></label><label>{t.arrival}<input name="arrivalTime" type="time" required/></label>
  {options&&options.modes.length>0&&<fieldset className="arrivalPick"><legend>{t.arrivalHow}</legend><select aria-label={t.arrivalHow} value={mode} onChange={e=>{const m=e.target.value;setMode(m);setHub(options.modes.find(x=>x.mode===m)?.hubs[0]?.key??"");setVehicle("")}}><option value="">{t.modeNone}</option>{options.modes.map(m=><option key={m.mode} value={m.mode}>{t[`mode_${m.mode}`]??m.mode}</option>)}</select>
   {current&&current.hubs.length>1&&<label>{t.hub}<select value={hub} onChange={e=>setHub(e.target.value)}>{current.hubs.map(h=><option key={h.key} value={h.key}>{h.name}</option>)}</select></label>}
   {current?.transfer&&options.vehicles.length>0&&<label>{t.transfer}<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">{t.transferNone}</option>{options.vehicles.map(v=><option key={v.key} value={v.key}>{v.name} · {price(v.priceCents)}</option>)}</select>{vehicle&&<small>{t.transferNote}</small>}</label>}
  </fieldset>}
  <label>{t.documentType}<select name="documentType"><option value="passport">{t.passport}</option><option value="identity_card">{t.identity}</option></select></label><label>{t.documentNumber}<input name="documentNumber" required/></label><label>{t.dob}<input name="dateOfBirth" type="date" required/></label><label>{t.travel}<textarea name="travelDetails" maxLength={500}/></label><label>{t.requests}<textarea name="specialRequests" maxLength={1000}/></label><label><input type="checkbox" name="luggageAssistance"/> {t.luggage}</label><label><input type="checkbox" name="emailMarketingConsent"/> {t.emailConsent}</label><label><input type="checkbox" name="whatsappMarketingConsent"/> {t.whatsappConsent}</label><button disabled={!token||busy}>{t.submit}</button><p role="status">{message}</p></form></main>}
