import Stripe from "stripe";
import {z} from "zod";
import {db,withTransaction} from "@/lib/db";
import {env} from "@/lib/env";
import {stripeCredentials} from "@/lib/provider-connections";
import {hashToken} from "@/lib/security/tokens";
const input=z.object({token:z.string().min(32).max(200)});
async function find(token:string){return db().query(`SELECT l.id,l.status,l.expires_at,l.checkout_expires_at,l.checkout_url,b.reference,b.balance_cents,b.guest_email,b.guest_name,b.guest_language,b.status AS booking_status FROM balance_payment_links l JOIN bookings b ON b.id=l.booking_id AND b.owner_id=l.owner_id WHERE l.owner_id=$1 AND l.token_hash=$2 LIMIT 1`,[env().PMS_OWNER_ID,hashToken(token)])}
export async function GET(request:Request){const token=new URL(request.url).searchParams.get("token")??"";if(token.length<32)return Response.json({ok:false,error:"INVALID_LINK"},{status:404});const result=await find(token),row=result.rows[0];if(!row||row.expires_at<Date.now()||!["active","checkout_pending"].includes(row.status)||["cancelled","no_show"].includes(row.booking_status))return Response.json({ok:false,error:"INVALID_LINK"},{status:404});return Response.json({ok:true,reference:row.reference,balanceCents:Number(row.balance_cents),guestName:row.guest_name},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:Request){try{const {token}=input.parse(await request.json()),settings=env(),credentials=await stripeCredentials(settings.PMS_OWNER_ID);if(!credentials?.secretKey)return Response.json({ok:false,error:"PAYMENT_NOT_CONFIGURED"},{status:503});const stripe=new Stripe(credentials.secretKey);const url=await withTransaction(async client=>{const result=await client.query(`SELECT l.*,b.reference,b.balance_cents,b.guest_email,b.guest_language,b.status AS booking_status FROM balance_payment_links l JOIN bookings b ON b.id=l.booking_id AND b.owner_id=l.owner_id WHERE l.owner_id=$1 AND l.token_hash=$2 FOR UPDATE OF l,b`,[settings.PMS_OWNER_ID,hashToken(token)]),row=result.rows[0],now=Date.now();if(!row||row.expires_at<=now||!["active","checkout_pending"].includes(row.status)||["cancelled","no_show"].includes(row.booking_status))throw Error("INVALID_LINK");const amount=Number(row.balance_cents);if(!Number.isSafeInteger(amount)||amount<=0)throw Error("NOTHING_DUE");if(row.status==="checkout_pending"&&row.checkout_expires_at>now){if(Number(row.amount_cents)!==amount)throw Error("PAYMENT_IN_PROGRESS");return String(row.checkout_url)}const session=await stripe.checkout.sessions.create({mode:"payment",customer_email:row.guest_email??undefined,line_items:[{quantity:1,price_data:{currency:"eur",unit_amount:amount,product_data:{name:`Hotel Corali · ${row.reference} · balance`}}}],expires_at:Math.floor((now+31*60_000)/1000),success_url:`${settings.BOOKING_ORIGIN}/pay-balance?status=success&lang=${row.guest_language}`,cancel_url:`${settings.BOOKING_ORIGIN}/pay-balance?token=${encodeURIComponent(token)}&status=cancelled&lang=${row.guest_language}`,metadata:{kind:"balance",owner_id:settings.PMS_OWNER_ID,booking_id:String(row.booking_id),balance_link_id:String(row.id),amount_cents:String(amount)}},{idempotencyKey:`corali-balance-${row.id}-${amount}-${Math.floor(now/1860000)}`});if(!session.url)throw Error("CHECKOUT_FAILED");await client.query(`UPDATE balance_payment_links SET status='checkout_pending',checkout_session_id=$1,checkout_url=$2,checkout_expires_at=$3,amount_cents=$4 WHERE id=$5`,[session.id,session.url,now+31*60_000,amount,row.id]);return session.url});return Response.json({ok:true,url})}catch(e){const error=e instanceof Error?e.message:"CHECKOUT_FAILED";return Response.json({ok:false,error},{status:["INVALID_LINK","NOTHING_DUE"].includes(error)?404:error==="PAYMENT_IN_PROGRESS"?409:500})}}
