"use client";
import {useState} from "react";
import {permissionKeys,parsePermissions,type Permission} from "@/lib/security/permissions";
type U={id:number;username:string;display_name:string;email:string;role:string;active:number;permissions_json:string};
const labels:Record<Permission,string>={"dashboard.read":"Αρχική · προβολή","dashboard.write":"Σημειώσεις · αλλαγές","reservations.read":"Κρατήσεις · προβολή","reservations.write":"Κρατήσεις · αλλαγές","reservations.create":"Κρατήσεις · δημιουργία","reservations.edit":"Κρατήσεις · επεξεργασία","folios.read":"Οικονομικά · προβολή","folios.write":"Οικονομικά · αλλαγές","rooms.read":"Δωμάτια · προβολή","rooms.write":"Δωμάτια · αλλαγές","rooms.create":"Κατάλογος · δημιουργία","rooms.edit":"Κατάλογος · επεξεργασία","housekeeping.read":"Housekeeping · προβολή","housekeeping.write":"Housekeeping · αλλαγές","pricing.read":"Τιμές · προβολή","pricing.write":"Τιμές · αλλαγές","pricing.create":"Τιμές · δημιουργία","pricing.edit":"Τιμές · επεξεργασία","reports.read":"Αναφορές · προβολή","integrations.read":"Συνδέσεις · προβολή","integrations.write":"Συνδέσεις · αλλαγές","users.manage":"Χρήστες · διαχείριση"};
const roles=[{value:"reception",label:"Υποδοχή"},{value:"housekeeping",label:"Housekeeping"},{value:"readonly",label:"Μόνο ανάγνωση"},{value:"admin",label:"Διαχειριστής"}];
export function UsersManager({initial,currentUserId}:{initial:U[];currentUserId:number}){
 const [users,setUsers]=useState(initial),[msg,setMsg]=useState(""),[editing,setEditing]=useState<number|null>(null),[overrides,setOverrides]=useState<Partial<Record<Permission,boolean>>>({}),[busy,setBusy]=useState(false);
 async function send(method:"POST"|"PATCH",body:object){setBusy(true);try{const r=await fetch("/api/pms/users",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setMsg(j.error??"Η αποθήκευση απέτυχε.");return false}setUsers(v=>method==="POST"?[...v,j.user]:v.map(x=>x.id===j.user.id?j.user:x));setMsg(method==="POST"?"Ο χρήστης δημιουργήθηκε.":"Οι αλλαγές αποθηκεύτηκαν. Οι προηγούμενες συνεδρίες ακυρώθηκαν όπου απαιτείται.");return true}catch{setMsg("Η σύνδεση απέτυχε.");return false}finally{setBusy(false)}}
 async function add(f:FormData){const body=Object.fromEntries(f);if(await send("POST",body))setEditing(null)}
 async function update(f:FormData){if(editing===null)return;const body=Object.fromEntries(f);if(!body.password)delete body.password;if(await send("PATCH",{id:editing,...body,...(editing===currentUserId?{}:{permissions:overrides})}))setEditing(null)}
 async function toggle(u:U){await send("PATCH",{id:u.id,active:!Boolean(u.active)})}
 return <><form action={add} className="adminForm"><input name="username" placeholder="Username" required/><input name="displayName" placeholder="Ονοματεπώνυμο" required/><input name="email" type="email" placeholder="Email" required/><select name="role">{roles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select><input name="password" type="password" minLength={12} placeholder="Κωδικός 12+ χαρακτήρων" required/><button disabled={busy}>Προσθήκη χρήστη</button></form><p className="notice" role="status">{msg}</p><div className="tableWrap"><table><thead><tr><th>Χρήστης</th><th>Email</th><th>Ρόλος</th><th>Κατάσταση</th><th>Ενέργειες</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.display_name}<small>{u.username}</small></td><td>{u.email}</td><td>{u.role}</td><td>{u.active?"Ενεργός":"Ανενεργός"}</td><td><button disabled={busy} onClick={()=>{setEditing(u.id);setOverrides(parsePermissions(u.permissions_json))}}>Επεξεργασία</button> {u.id!==currentUserId&&<button disabled={busy} onClick={()=>toggle(u)}>{u.active?"Απενεργοποίηση":"Ενεργοποίηση"}</button>}</td></tr>)}</tbody></table></div>{editing!==null&&users.filter(u=>u.id===editing).map(u=><form key={u.id} action={update} className="policyForm userEditor"><h2>Επεξεργασία: {u.display_name}</h2><label>Ονοματεπώνυμο<input name="displayName" defaultValue={u.display_name} required/></label><label>Email<input name="email" type="email" defaultValue={u.email} required/></label>{u.id!==currentUserId&&<label>Ρόλος<select name="role" defaultValue={u.role}>{roles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label>}<label>Νέος κωδικός<input name="password" type="password" minLength={12} placeholder="Κενό = χωρίς αλλαγή"/></label>{u.id!==currentUserId&&<fieldset><legend>Εξατομικευμένα δικαιώματα</legend><p>«Βάσει ρόλου» εφαρμόζει τα προεπιλεγμένα δικαιώματα του ρόλου.</p>{permissionKeys.map(key=><label className="permissionRow" key={key}>{labels[key]}<select value={overrides[key]===undefined?"default":String(overrides[key])} onChange={e=>setOverrides(v=>{const next={...v};if(e.target.value==="default")delete next[key];else next[key]=e.target.value==="true";return next})}><option value="default">Βάσει ρόλου</option><option value="true">Επιτρέπεται</option><option value="false">Απαγορεύεται</option></select></label>)}</fieldset>}<div className="actions"><button disabled={busy}>Αποθήκευση</button><button type="button" onClick={()=>setEditing(null)}>Άκυρο</button></div></form>)}</>
}
