"use client";
import {useEffect,useState} from "react";
import {bookingLanguages} from "@/lib/booking-i18n";
type Row={id:number;base_name:string;name_translations_json:string;description_translations_json?:string};
type Kind="rooms"|"plans"|"extras"|"charges";
const labels:Record<Kind,string>={rooms:"Κατηγορίες δωματίων",plans:"Rate plans",extras:"Extras",charges:"Υποχρεωτικές χρεώσεις"};
function parse(value:string|undefined):Record<string,string>{try{return JSON.parse(value??"{}") as Record<string,string>}catch{return {}}}
export function TranslationEditor(){const [data,setData]=useState<Record<string,Row[]>>({}),[status,setStatus]=useState("");useEffect(()=>{fetch("/api/pms/translations").then(r=>r.json()).then(j=>setData(j.data??{})).catch(()=>setStatus("Αποτυχία φόρτωσης"))},[]);
 async function save(kind:Kind,row:Row,form:FormData){setStatus("");const names:Record<string,string>={},descriptions:Record<string,string>={};for(const lang of bookingLanguages){names[lang]=String(form.get(`name_${lang}`)??"");descriptions[lang]=String(form.get(`description_${lang}`)??"")}try{const r=await fetch("/api/pms/translations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id:row.id,names,descriptions})});if(!r.ok)throw Error();setStatus(`Αποθηκεύτηκε: ${row.base_name}`);setData(current=>({...current,[kind]:current[kind].map(x=>x.id===row.id?{...x,name_translations_json:JSON.stringify(names),description_translations_json:JSON.stringify(descriptions)}:x)}))}catch{setStatus("Η αποθήκευση απέτυχε")}}
 return <div className="translationsEditor"><p role="status">{status}</p>{(Object.keys(labels) as Kind[]).filter(kind=>data[kind]).map(kind=><section key={kind}><h2>{labels[kind]}</h2>{data[kind].map(row=><details key={row.id}><summary>{row.base_name}</summary><form action={form=>save(kind,row,form)}><div className="translationFields">{bookingLanguages.map(lang=><fieldset key={lang}><legend>{lang.toUpperCase()}</legend><label>Όνομα<input name={`name_${lang}`} defaultValue={parse(row.name_translations_json)[lang]??""} maxLength={2000}/></label>{row.description_translations_json!==undefined&&<label>Περιγραφή<textarea name={`description_${lang}`} defaultValue={parse(row.description_translations_json)[lang]??""} maxLength={2000}/></label>}</fieldset>)}</div><button type="submit">Αποθήκευση</button></form></details>)}</section>)}</div>}
