"use client";
import {useEffect,useState} from "react";
import {bookingLanguages,type BookingLanguage} from "@/lib/booking-i18n";
import {defaultTemplates,messageEvents,type MessageEvent,type MessageTemplates} from "@/lib/message-templates";
const labels:Record<MessageEvent,string>={confirmation:"Επιβεβαίωση νέας κράτησης",checkin:"Σύνδεσμος online check-in",balance:"Υπόλοιπο και σύνδεσμος Stripe",review:"Αίτημα κριτικής μετά τη διαμονή"};
type Settings={enabled:boolean;emailEnabled:boolean;whatsappEnabled:boolean;checkinDaysBefore:number;balanceDaysBeforeCheckout:number;reviewDaysAfterCheckout:number;sendHour:number;reviewUrl:string;events:Record<MessageEvent,boolean>;templates:MessageTemplates};
type Delivery={id:number;event_key:string;channel:string;scheduled_at:number;status:string;attempts:number;last_error:string|null;sent_at:number|null;reference:string};
const initial:Settings={enabled:false,emailEnabled:true,whatsappEnabled:false,checkinDaysBefore:3,balanceDaysBeforeCheckout:1,reviewDaysAfterCheckout:2,sendHour:10,reviewUrl:"",events:{confirmation:true,checkin:true,balance:true,review:false},templates:defaultTemplates};
export function AutomationsManager({editable}:{editable:boolean}){const [settings,setSettings]=useState(initial),[history,setHistory]=useState<Delivery[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/pms/automations").then(r=>r.json()).then(j=>{if(j.ok){setSettings(j.settings);setHistory(j.history)}}).catch(()=>setMessage("Η φόρτωση απέτυχε."))},[]);
 function setTemplate(event:MessageEvent,lang:BookingLanguage,field:"subject"|"body"|"whatsappTemplate",value:string){setSettings(s=>({...s,templates:{...s.templates,[event]:{...s.templates[event],[lang]:{...s.templates[event][lang],[field]:value}}}}))}
 async function retry(id:number){try{const r=await fetch("/api/pms/automations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(!r.ok)throw Error();setHistory(rows=>rows.map(row=>row.id===id?{...row,status:"pending",last_error:null}:row));setMessage("Η αποστολή προγραμματίστηκε ξανά.")}catch{setMessage("Η επανάληψη απέτυχε.")}}
 async function save(){setBusy(true);setMessage("");try{const r=await fetch("/api/pms/automations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)}),j=await r.json();if(!r.ok)throw Error(j.error??"SAVE_FAILED");setMessage("Οι ρυθμίσεις αποθηκεύτηκαν.")}catch(e){setMessage(`Αποτυχία: ${e instanceof Error?e.message:"SAVE_FAILED"}`)}finally{setBusy(false)}}
 return <div className="automationEditor"><p role="status" className="notice">{message}</p><section className="card"><h2>Αποστολή και χρονισμός</h2><label><input type="checkbox" checked={settings.enabled} disabled={!editable} onChange={e=>setSettings(s=>({...s,enabled:e.target.checked}))}/> Ενεργοποίηση αυτοματισμών</label><label><input type="checkbox" checked={settings.emailEnabled} disabled={!editable} onChange={e=>setSettings(s=>({...s,emailEnabled:e.target.checked}))}/> Email</label><label><input type="checkbox" checked={settings.whatsappEnabled} disabled={!editable} onChange={e=>setSettings(s=>({...s,whatsappEnabled:e.target.checked}))}/> WhatsApp με εγκεκριμένα Meta templates και συγκατάθεση</label><div className="translationFields"><label>Pre-check-in: ημέρες πριν την άφιξη<input type="number" min="1" max="30" value={settings.checkinDaysBefore} disabled={!editable} onChange={e=>setSettings(s=>({...s,checkinDaysBefore:Number(e.target.value)}))}/></label><label>Υπόλοιπο: ημέρες πριν το check-out<input type="number" min="0" max="30" value={settings.balanceDaysBeforeCheckout} disabled={!editable} onChange={e=>setSettings(s=>({...s,balanceDaysBeforeCheckout:Number(e.target.value)}))}/></label><label>Κριτική: ημέρες μετά το check-out<input type="number" min="1" max="30" value={settings.reviewDaysAfterCheckout} disabled={!editable} onChange={e=>setSettings(s=>({...s,reviewDaysAfterCheckout:Number(e.target.value)}))}/></label><label>Ώρα αποστολής (Ελλάδα)<input type="number" min="0" max="23" value={settings.sendHour} disabled={!editable} onChange={e=>setSettings(s=>({...s,sendHour:Number(e.target.value)}))}/></label><label>Σύνδεσμος κριτικής Google / TripAdvisor<input type="url" value={settings.reviewUrl} disabled={!editable} onChange={e=>setSettings(s=>({...s,reviewUrl:e.target.value}))}/></label></div></section>
 {messageEvents.map(event=><section className="card" key={event}><h2>{labels[event]}</h2><label><input type="checkbox" checked={settings.events[event]} disabled={!editable} onChange={e=>setSettings(s=>({...s,events:{...s.events,[event]:e.target.checked}}))}/> Ενεργό</label><p>{event==="confirmation"?"Αμέσως μετά την επιβεβαίωση (εκτέλεση cron).":event==="checkin"?`${settings.checkinDaysBefore} ημέρες πριν την άφιξη.`:event==="balance"?`${settings.balanceDaysBeforeCheckout} ημέρες πριν την αναχώρηση, μόνο αν υπάρχει υπόλοιπο.`:`${settings.reviewDaysAfterCheckout} ημέρες μετά την αναχώρηση.`}</p><div className="translationFields">{bookingLanguages.map(lang=><fieldset key={lang}><legend>{lang.toUpperCase()}</legend><label>Θέμα email<input value={settings.templates[event][lang].subject} disabled={!editable} onChange={e=>setTemplate(event,lang,"subject",e.target.value)}/></label><label>Κείμενο email<textarea rows={5} value={settings.templates[event][lang].body} disabled={!editable} onChange={e=>setTemplate(event,lang,"body",e.target.value)}/></label><label>Όνομα εγκεκριμένου WhatsApp template<input value={settings.templates[event][lang].whatsappTemplate} disabled={!editable} placeholder="π.χ. hotel_checkin_el" onChange={e=>setTemplate(event,lang,"whatsappTemplate",e.target.value)}/></label></fieldset>)}</div></section>)}
 <p>Μεταβλητές: <code>{"{{name}}, {{reference}}, {{checkIn}}, {{checkOut}}, {{amount}}, {{link}}"}</code>. Τα WhatsApp templates πρέπει να είναι εγκεκριμένα από τη Meta. Παράμετροι κατά σειρά: επιβεβαίωση (κωδικός, άφιξη, αναχώρηση), check-in (όνομα, σύνδεσμος), υπόλοιπο (όνομα, ποσό, σύνδεσμος), κριτική (όνομα, σύνδεσμος).</p>{editable&&<button className="primary" type="button" disabled={busy} onClick={save}>Αποθήκευση αυτοματισμών</button>}
 <section className="card"><h2>Ιστορικό αποστολών</h2><div className="tableWrap"><table><thead><tr><th>Κράτηση</th><th>Μήνυμα</th><th>Κανάλι</th><th>Χρόνος</th><th>Κατάσταση</th><th>Προσπάθειες</th><th>Σφάλμα</th><th>Ενέργεια</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{x.reference}</td><td>{labels[x.event_key as MessageEvent]??x.event_key}</td><td>{x.channel}</td><td>{new Date(Number(x.scheduled_at)).toLocaleString("el-GR")}</td><td>{x.status}</td><td>{x.attempts}</td><td>{x.last_error??"—"}</td><td>{editable&&x.status==="failed"&&<button type="button" onClick={()=>retry(x.id)}>Επανάληψη</button>}</td></tr>)}</tbody></table></div></section></div>
}
