"use client";
import {useEffect,useState} from "react";
import {bookingLanguages,type BookingLanguage} from "@/lib/booking-i18n";
import {defaultTemplates,messageEvents,type MessageEvent,type MessageTemplates} from "@/lib/message-templates";
const labels:Record<MessageEvent,string>={confirmation:"Επιβεβαίωση νέας κράτησης",pre_arrival:"72 ώρες πριν την άφιξη · οδηγίες άφιξης",checkin:"Σύνδεσμος online check-in",welcome:"Καλωσόρισμα την ημέρα άφιξης",balance:"Υπόλοιπο και σύνδεσμος Stripe",pre_departure:"Πριν την αναχώρηση",review:"Κριτική μετά τη διαμονή (φίλτρο 4–5★ / 1–3★)"};
type Settings={enabled:boolean;emailEnabled:boolean;whatsappEnabled:boolean;checkinDaysBefore:number;balanceDaysBeforeCheckout:number;reviewDaysAfterCheckout:number;sendHour:number;preArrivalHour:number;welcomeHour:number;preDepartureHour:number;reviewUrl:string;tripadvisorUrl:string;events:Record<MessageEvent,boolean>;templates:MessageTemplates};
type Delivery={id:number;event_key:string;channel:string;scheduled_at:number;status:string;attempts:number;last_error:string|null;sent_at:number|null;reference:string};
const initial:Settings={enabled:false,emailEnabled:true,whatsappEnabled:false,checkinDaysBefore:3,balanceDaysBeforeCheckout:1,reviewDaysAfterCheckout:2,sendHour:10,preArrivalHour:15,welcomeHour:16,preDepartureHour:18,reviewUrl:"",tripadvisorUrl:"",events:{confirmation:true,pre_arrival:true,checkin:true,welcome:true,balance:true,pre_departure:true,review:false},templates:defaultTemplates};
export function AutomationsManager({editable}:{editable:boolean}){const [settings,setSettings]=useState(initial),[history,setHistory]=useState<Delivery[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/pms/automations").then(r=>r.json()).then(j=>{if(j.ok){setSettings(j.settings);setHistory(j.history)}}).catch(()=>setMessage("Η φόρτωση απέτυχε."))},[]);
 function setTemplate(event:MessageEvent,lang:BookingLanguage,field:"subject"|"body"|"whatsappTemplate",value:string){setSettings(s=>({...s,templates:{...s.templates,[event]:{...s.templates[event],[lang]:{...s.templates[event][lang],[field]:value}}}}))}
 async function retry(id:number){try{const r=await fetch("/api/pms/automations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(!r.ok)throw Error();setHistory(rows=>rows.map(row=>row.id===id?{...row,status:"pending",last_error:null}:row));setMessage("Η αποστολή προγραμματίστηκε ξανά.")}catch{setMessage("Η επανάληψη απέτυχε.")}}
 async function save(){setBusy(true);setMessage("");try{const r=await fetch("/api/pms/automations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)}),j=await r.json();if(!r.ok)throw Error(j.error??"SAVE_FAILED");setMessage("Οι ρυθμίσεις αποθηκεύτηκαν.")}catch(e){setMessage(`Αποτυχία: ${e instanceof Error?e.message:"SAVE_FAILED"}`)}finally{setBusy(false)}}
 return <div className="automationEditor"><p role="status" className="notice">{message}</p><div className="autoTop"><section className="card"><h2>Αποστολή και χρονισμός</h2><label><input type="checkbox" checked={settings.enabled} disabled={!editable} onChange={e=>setSettings(s=>({...s,enabled:e.target.checked}))}/> Ενεργοποίηση αυτοματισμών</label><label><input type="checkbox" checked={settings.emailEnabled} disabled={!editable} onChange={e=>setSettings(s=>({...s,emailEnabled:e.target.checked}))}/> Email</label><label><input type="checkbox" checked={settings.whatsappEnabled} disabled={!editable} onChange={e=>setSettings(s=>({...s,whatsappEnabled:e.target.checked}))}/> WhatsApp με εγκεκριμένα Meta templates και συγκατάθεση</label><div className="translationFields"><label>Pre-check-in: ημέρες πριν την άφιξη<input type="number" min="1" max="30" value={settings.checkinDaysBefore} disabled={!editable} onChange={e=>setSettings(s=>({...s,checkinDaysBefore:Number(e.target.value)}))}/></label><label>Υπόλοιπο: ημέρες πριν το check-out<input type="number" min="0" max="30" value={settings.balanceDaysBeforeCheckout} disabled={!editable} onChange={e=>setSettings(s=>({...s,balanceDaysBeforeCheckout:Number(e.target.value)}))}/></label><label>Κριτική: ημέρες μετά το check-out<input type="number" min="1" max="30" value={settings.reviewDaysAfterCheckout} disabled={!editable} onChange={e=>setSettings(s=>({...s,reviewDaysAfterCheckout:Number(e.target.value)}))}/></label><label>Ώρα αποστολής (Ελλάδα)<input type="number" min="0" max="23" value={settings.sendHour} disabled={!editable} onChange={e=>setSettings(s=>({...s,sendHour:Number(e.target.value)}))}/></label><label>72h πριν: ώρα αποστολής<input type="number" min="0" max="23" value={settings.preArrivalHour} disabled={!editable} onChange={e=>setSettings(s=>({...s,preArrivalHour:Number(e.target.value)}))}/></label><label>Καλωσόρισμα: ώρα<input type="number" min="0" max="23" value={settings.welcomeHour} disabled={!editable} onChange={e=>setSettings(s=>({...s,welcomeHour:Number(e.target.value)}))}/></label><label>Πριν την αναχώρηση: ώρα (προηγούμενη ημέρα)<input type="number" min="0" max="23" value={settings.preDepartureHour} disabled={!editable} onChange={e=>setSettings(s=>({...s,preDepartureHour:Number(e.target.value)}))}/></label><label>Σύνδεσμος κριτικής Google<input type="url" value={settings.reviewUrl} disabled={!editable} onChange={e=>setSettings(s=>({...s,reviewUrl:e.target.value}))}/></label><label>Σύνδεσμος κριτικής TripAdvisor<input type="url" value={settings.tripadvisorUrl} disabled={!editable} onChange={e=>setSettings(s=>({...s,tripadvisorUrl:e.target.value}))}/></label></div></section><TestSend editable={editable} templates={settings.templates}/></div>
 <div className="autoEvents">{messageEvents.map(event=><section className="card" key={event}><h2>{labels[event]}</h2><label><input type="checkbox" checked={settings.events[event]} disabled={!editable} onChange={e=>setSettings(s=>({...s,events:{...s.events,[event]:e.target.checked}}))}/> Ενεργό</label><p>{event==="confirmation"?"Αμέσως μετά την επιβεβαίωση (εκτέλεση cron).":event==="pre_arrival"?`3 ημέρες (72 ώρες) πριν την άφιξη στις ${settings.preArrivalHour}:00, με τις οδηγίες άφιξης του επισκέπτη ({{arrival}}) και σύνδεσμο check-in αν λείπει.`:event==="checkin"?`${settings.checkinDaysBefore} ημέρες πριν την άφιξη.`:event==="welcome"?`Την ημέρα άφιξης στις ${settings.welcomeHour}:00.`:event==="balance"?`${settings.balanceDaysBeforeCheckout} ημέρες πριν την αναχώρηση, μόνο αν υπάρχει υπόλοιπο.`:event==="pre_departure"?`Την προηγούμενη της αναχώρησης στις ${settings.preDepartureHour}:00, σε επισκέπτες εντός ξενοδοχείου.`:`${settings.reviewDaysAfterCheckout} ημέρες μετά την αναχώρηση. Ο σύνδεσμος ανοίγει σελίδα αξιολόγησης: 4–5★ → Google/TripAdvisor, 1–3★ → ιδιωτική φόρμα προς τη διεύθυνση.`}</p><div className="translationFields">{bookingLanguages.map(lang=><fieldset key={lang}><legend>{lang.toUpperCase()}</legend><label>Θέμα email<input value={settings.templates[event][lang].subject} disabled={!editable} onChange={e=>setTemplate(event,lang,"subject",e.target.value)}/></label><label>Κείμενο email<textarea rows={5} value={settings.templates[event][lang].body} disabled={!editable} onChange={e=>setTemplate(event,lang,"body",e.target.value)}/></label><label>Όνομα εγκεκριμένου WhatsApp template<input value={settings.templates[event][lang].whatsappTemplate} disabled={!editable} placeholder="π.χ. hotel_checkin_el" onChange={e=>setTemplate(event,lang,"whatsappTemplate",e.target.value)}/></label></fieldset>)}</div></section>)}
</div>
 <p>Μεταβλητές: <code>{"{{name}}, {{reference}}, {{checkIn}}, {{checkOut}}, {{amount}}, {{link}}, {{arrival}}"}</code>. Τα WhatsApp templates πρέπει να είναι εγκεκριμένα από τη Meta. Παράμετροι κατά σειρά: επιβεβαίωση (κωδικός, άφιξη, αναχώρηση), check-in (όνομα, σύνδεσμος), υπόλοιπο (όνομα, ποσό, σύνδεσμος), 72h (όνομα, άφιξη, σύνδεσμος check-in), καλωσόρισμα (όνομα), πριν την αναχώρηση (όνομα, αναχώρηση), κριτική (όνομα, σύνδεσμος).</p>{editable&&<button className="primary" type="button" disabled={busy} onClick={save}>Αποθήκευση αυτοματισμών</button>}
 <section className="card"><h2>Ιστορικό αποστολών</h2><div className="tableWrap"><table><thead><tr><th>Κράτηση</th><th>Μήνυμα</th><th>Κανάλι</th><th>Χρόνος</th><th>Κατάσταση</th><th>Προσπάθειες</th><th>Σφάλμα</th><th>Ενέργεια</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{x.reference}</td><td>{labels[x.event_key as MessageEvent]??x.event_key}</td><td>{x.channel}</td><td>{new Date(Number(x.scheduled_at)).toLocaleString("el-GR")}</td><td>{x.status}</td><td>{x.attempts}</td><td>{x.last_error??"—"}</td><td>{editable&&x.status==="failed"&&<button type="button" onClick={()=>retry(x.id)}>Επανάληψη</button>}</td></tr>)}</tbody></table></div></section></div>
}

type TestResult={ok:boolean;error?:string;hint?:string;detail?:string;server?:string|null;template?:string;messageId?:string};
const hints:Record<string,string>={not_configured:"Δεν έχουν οριστεί στοιχεία σύνδεσης. Συμπληρώστε τα στο PMS → Integrations (Email / SMTP ή WhatsApp Business) και ενεργοποιήστε τα.",auth:"Ο server δεν δέχτηκε όνομα χρήστη / κωδικό. Ελέγξτε τον κωδικό SMTP (σε Gmail/Outlook χρειάζεται app password).",connection:"Δεν έγινε σύνδεση με τον SMTP server (λήξη χρόνου ή άρνηση). Ελέγξτε host και θύρα (587 STARTTLS ή 465 SSL). Σε cPanel η εξερχόμενη σύνδεση σε εξωτερικό SMTP (π.χ. Gmail) συχνά μπλοκάρεται («SMTP Restrictions»): χρησιμοποιήστε το mail του ίδιου του server (π.χ. mail.hotelcorali.gr, θύρα 465, λογαριασμός email του cPanel) ή ζητήστε από τον πάροχο να το επιτρέψει.",rejected:"Ο server απέρριψε τον παραλήπτη ή τον αποστολέα. Το «From» πρέπει να ανήκει στον λογαριασμό SMTP.",token:"Το access token του WhatsApp έληξε ή δεν είναι έγκυρο. Δημιουργήστε μόνιμο token (System User) στο Meta Business.",recipient_not_allowed:"Με αριθμό δοκιμών της Meta μπορείτε να στείλετε μόνο σε αριθμούς που έχετε προσθέσει στη λίστα παραληπτών του app.",template:"Το template δεν υπάρχει ή δεν είναι εγκεκριμένο για αυτή τη γλώσσα, ή ο αριθμός παραμέτρων διαφέρει.",undeliverable:"Ο αριθμός δεν έχει WhatsApp ή δεν μπορεί να λάβει μήνυμα.",settings:"Ελέγξτε Phone number ID και έκδοση API στο Integrations.",permission:"Το token δεν έχει δικαίωμα whatsapp_business_messaging για αυτόν τον αριθμό.",no_template:"Δεν έχει οριστεί όνομα WhatsApp template για αυτό το μήνυμα και τη γλώσσα.",number:"Γράψτε τον αριθμό με κωδικό χώρας, π.χ. +30 69…",proxy:"Ο web server διέκοψε το αίτημα πριν απαντήσει η εφαρμογή (συνήθως όριο χρόνου του proxy). Δοκιμάστε ξανά· αν επαναληφθεί, ελέγξτε το SMTP host/θύρα.",other:"Δείτε τον κωδικό σφάλματος."};
function TestSend({editable,templates}:{editable:boolean;templates:MessageTemplates}){
 const [channel,setChannel]=useState<"email"|"whatsapp">("email"),[to,setTo]=useState(""),[event,setEvent]=useState<MessageEvent>("confirmation"),[lang,setLang]=useState<BookingLanguage>("el"),[mode,setMode]=useState<"hello_world"|"event">("hello_world"),[busy,setBusy]=useState(false),[result,setResult]=useState<TestResult|null>(null);
 async function send(){setBusy(true);setResult(null);try{const r=await fetch("/api/pms/automations/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(channel==="email"?{channel,to,event,lang}:{channel,to,mode,event,lang}),signal:AbortSignal.timeout(45_000)});const j=await r.json().catch(()=>({ok:false,error:`HTTP_${r.status}`,hint:r.status>=500?"proxy":"other"}));setResult(r.status===429?{ok:false,error:"RATE_LIMITED",hint:"other",detail:"Πολλές δοκιμές· ξαναδοκιμάστε σε 10 λεπτά."}:j)}catch(e){setResult(e instanceof DOMException&&e.name==="TimeoutError"?{ok:false,error:"TIMEOUT",hint:"connection"}:{ok:false,error:"NETWORK",hint:"other"})}finally{setBusy(false)}}
 const waTemplate=templates[event]?.[lang]?.whatsappTemplate;
 return <section className="card testSend"><h2>Δοκιμαστική αποστολή</h2><p>Στέλνει ένα μήνυμα με δείγμα κράτησης, με τα αποθηκευμένα στοιχεία σύνδεσης και πρότυπα, για να δείτε αν το κανάλι λειτουργεί. Δεν καταγράφεται στο ιστορικό και δεν αφορά πραγματική κράτηση.</p>
 <div className="testTabs" role="tablist">{(["email","whatsapp"] as const).map(c=><button key={c} type="button" role="tab" aria-selected={channel===c} className={channel===c?"active":undefined} onClick={()=>{setChannel(c);setResult(null);setTo("")}}>{c==="email"?"✉️ Email":"💬 WhatsApp"}</button>)}</div>
 <label>{channel==="email"?"Email παραλήπτη":"Κινητό παραλήπτη (με κωδικό χώρας)"}<input type={channel==="email"?"email":"tel"} value={to} placeholder={channel==="email"?"name@example.com":"+30 69…"} onChange={e=>setTo(e.target.value)}/></label>
 {channel==="whatsapp"&&<><label className="testRadio"><input type="radio" name="waMode" checked={mode==="hello_world"} onChange={()=>setMode("hello_world")}/> Template «hello_world» της Meta (υπάρχει σε κάθε λογαριασμό · έλεγχος σύνδεσης)</label><label className="testRadio"><input type="radio" name="waMode" checked={mode==="event"} onChange={()=>setMode("event")}/> Το δικό σας template για ένα μήνυμα</label></>}
 {(channel==="email"||mode==="event")&&<div className="testPick"><label>Μήνυμα<select value={event} onChange={e=>setEvent(e.target.value as MessageEvent)}>{messageEvents.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></label><label>Γλώσσα<select value={lang} onChange={e=>setLang(e.target.value as BookingLanguage)}>{bookingLanguages.map(l=><option key={l} value={l}>{l.toUpperCase()}</option>)}</select></label></div>}
 {channel==="whatsapp"&&mode==="event"&&<small>Template: <code>{waTemplate||"— δεν έχει οριστεί —"}</code></small>}
 <button type="button" className="primary" disabled={!editable||busy||!to.trim()} onClick={send}>{busy?"Αποστολή…":"Αποστολή δοκιμής"}</button>{!editable&&<small> Χρειάζεται δικαίωμα επεξεργασίας Integrations.</small>}
 {result&&(result.ok?<p className="testResult ok" role="status">✅ {channel==="email"?`Το email στάλθηκε${result.server?` μέσω ${result.server}`:""}. Ελέγξτε τα εισερχόμενα (και τα ανεπιθύμητα).`:`Η Meta δέχτηκε το μήνυμα (template ${result.template}, id ${result.messageId}). Αν δεν φτάσει σε λίγα λεπτά, ελέγξτε ότι ο αριθμός έχει WhatsApp.`}</p>:<div className="testResult fail" role="alert"><b>❌ Αποτυχία: {result.error}</b>{result.detail&&<span>{result.detail}</span>}<span>{hints[result.hint??"other"]??hints.other}</span>{result.server&&<small>Server: {result.server}</small>}</div>)}
 </section>}
