import {bookingLanguages,type BookingLanguage} from "./booking-i18n.ts";
export const messageEvents=["confirmation","checkin","balance","review"] as const;
export type MessageEvent=typeof messageEvents[number];
export type MessageTemplate={subject:string;body:string;whatsappTemplate:string};
export type MessageTemplates=Record<MessageEvent,Record<BookingLanguage,MessageTemplate>>;
const translations:Record<BookingLanguage,Record<MessageEvent,[string,string]>>={
 en:{confirmation:["Your Hotel Corali reservation {{reference}}","Hello {{name}}, your reservation {{reference}} is confirmed for {{checkIn}} to {{checkOut}}. We look forward to welcoming you."],checkin:["Complete your online check-in · {{reference}}","Hello {{name}}, please complete your secure online check-in before arrival: {{link}}"],balance:["Balance due for your stay · {{reference}}","Hello {{name}}, the current balance for reservation {{reference}} is {{amount}}. Pay securely here: {{link}}. The amount will be checked again before payment."],review:["How was your stay at Hotel Corali?","Hello {{name}}, thank you for staying with us. You can share your experience here: {{link}}"]},
 el:{confirmation:["Επιβεβαίωση κράτησης {{reference}} · Hotel Corali","Αγαπητέ/ή {{name}}, η κράτησή σας {{reference}} επιβεβαιώθηκε για {{checkIn}} έως {{checkOut}}. Σας περιμένουμε!"],checkin:["Ηλεκτρονικό check-in · {{reference}}","Αγαπητέ/ή {{name}}, συμπληρώστε το ασφαλές ηλεκτρονικό check-in πριν από την άφιξη: {{link}}"],balance:["Υπόλοιπο κράτησης {{reference}}","Αγαπητέ/ή {{name}}, το τρέχον υπόλοιπο της κράτησης {{reference}} είναι {{amount}}. Πληρώστε με ασφάλεια εδώ: {{link}}. Το ποσό ελέγχεται ξανά πριν την πληρωμή."],review:["Πώς ήταν η διαμονή σας στο Hotel Corali;","Αγαπητέ/ή {{name}}, σας ευχαριστούμε για τη διαμονή σας. Μοιραστείτε την εμπειρία σας εδώ: {{link}}"]},
 fr:{confirmation:["Confirmation de réservation {{reference}} · Hotel Corali","Bonjour {{name}}, votre réservation {{reference}} est confirmée du {{checkIn}} au {{checkOut}}. À bientôt !"],checkin:["Pré-enregistrement en ligne · {{reference}}","Bonjour {{name}}, veuillez compléter votre pré-enregistrement sécurisé avant votre arrivée : {{link}}"],balance:["Solde de votre réservation {{reference}}","Bonjour {{name}}, le solde actuel de votre réservation {{reference}} est de {{amount}}. Payez ici en toute sécurité : {{link}}. Le montant sera vérifié avant paiement."],review:["Comment s’est passé votre séjour à l’Hotel Corali ?","Bonjour {{name}}, merci de votre visite. Partagez votre expérience ici : {{link}}"]},
 de:{confirmation:["Buchungsbestätigung {{reference}} · Hotel Corali","Hallo {{name}}, Ihre Buchung {{reference}} vom {{checkIn}} bis {{checkOut}} ist bestätigt. Wir freuen uns auf Sie!"],checkin:["Online-Check-in · {{reference}}","Hallo {{name}}, bitte erledigen Sie Ihren sicheren Online-Check-in vor der Anreise: {{link}}"],balance:["Offener Betrag für Buchung {{reference}}","Hallo {{name}}, der aktuelle Restbetrag Ihrer Buchung {{reference}} beträgt {{amount}}. Sicher bezahlen: {{link}}. Der Betrag wird vor der Zahlung erneut geprüft."],review:["Wie war Ihr Aufenthalt im Hotel Corali?","Hallo {{name}}, vielen Dank für Ihren Besuch. Teilen Sie Ihre Erfahrungen hier: {{link}}"]},
 it:{confirmation:["Conferma prenotazione {{reference}} · Hotel Corali","Ciao {{name}}, la prenotazione {{reference}} dal {{checkIn}} al {{checkOut}} è confermata. Ti aspettiamo!"],checkin:["Check-in online · {{reference}}","Ciao {{name}}, completa il check-in online sicuro prima del tuo arrivo: {{link}}"],balance:["Saldo prenotazione {{reference}}","Ciao {{name}}, il saldo attuale della prenotazione {{reference}} è {{amount}}. Paga in sicurezza qui: {{link}}. L’importo sarà verificato prima del pagamento."],review:["Com’è stato il soggiorno all’Hotel Corali?","Ciao {{name}}, grazie per aver soggiornato da noi. Condividi la tua esperienza qui: {{link}}"]},
 es:{confirmation:["Confirmación de reserva {{reference}} · Hotel Corali","Hola {{name}}, tu reserva {{reference}} del {{checkIn}} al {{checkOut}} está confirmada. ¡Te esperamos!"],checkin:["Registro en línea · {{reference}}","Hola {{name}}, completa el registro seguro en línea antes de llegar: {{link}}"],balance:["Saldo de la reserva {{reference}}","Hola {{name}}, el saldo actual de tu reserva {{reference}} es {{amount}}. Paga de forma segura aquí: {{link}}. El importe se comprobará antes del pago."],review:["¿Qué tal fue tu estancia en Hotel Corali?","Hola {{name}}, gracias por alojarte con nosotros. Comparte tu experiencia aquí: {{link}}"]}
};
export const defaultTemplates=Object.fromEntries(messageEvents.map(event=>[event,Object.fromEntries(bookingLanguages.map(lang=>[lang,{subject:translations[lang][event][0],body:translations[lang][event][1],whatsappTemplate:""}]))])) as MessageTemplates;
export function renderTemplate(text:string,values:Record<string,string>){return text.replace(/{{(name|reference|checkIn|checkOut|amount|link)}}/g,(_,key:string)=>values[key]??"")}
export function requiredVariables(event:MessageEvent){return event==="confirmation"?["reference"]:event==="balance"?["amount","link"]:["link"]}
