import {z} from "zod";
import {requireApiUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {can} from "@/lib/security/permissions";
import {assertTrustedOrigin} from "@/lib/security/origin";
const weekdays=z.array(z.number().int().min(0).max(6)).max(7);
const codes=z.array(z.string().trim().min(1).max(120)).max(100);
const input=z.discriminatedUnion("kind",[
 z.object({kind:z.literal("special"),id:z.number().positive().optional(),name:z.string().min(2).max(120),startsOn:z.iso.date(),endsOn:z.iso.date(),adjustmentType:z.enum(["percentage","fixed"]),adjustmentValue:z.number().int().min(0).max(1_000_000),operation:z.enum(["charge","discount"]),minimumStay:z.number().int().min(1).max(365),weekdays:weekdays.default([]),roomCodes:codes.default([]),ratePlanKeys:codes.default([]),active:z.boolean()}),
 z.object({kind:z.literal("restriction"),id:z.number().positive().optional(),name:z.string().min(2).max(120),startsOn:z.iso.date(),endsOn:z.iso.date(),minimumStay:z.number().int().min(1).max(365),maximumStay:z.number().int().min(1).max(365).nullable(),closedArrivalWeekdays:weekdays,closedDepartureWeekdays:weekdays,roomCodes:codes.default([]),ratePlanKeys:codes.default([]),active:z.boolean()})
]);
export async function POST(request:Request){const u=await requireApiUser("pricing.read");if(u instanceof Response)return u;try{assertTrustedOrigin(request);const x=input.parse(await request.json());if(!can(u.role,x.id?"pricing.edit":"pricing.create",u.permissions))return Response.json({ok:false,error:"FORBIDDEN"},{status:403});if(x.endsOn<x.startsOn||x.kind==="restriction"&&x.maximumStay!==null&&x.maximumStay<x.minimumStay)throw Error("INVALID_DATES");const now=Date.now();let result;
 if(x.kind==="special")result=await db().query(x.id?`UPDATE special_prices SET name=$1,starts_on=$2,ends_on=$3,adjustment_type=$4,adjustment_value=$5,operation=$6,minimum_stay=$7,active=$8,weekdays=$9,room_codes=$10,rate_plan_keys=$11,updated_at=$12 WHERE owner_id=$13 AND id=$14 RETURNING id`:`INSERT INTO special_prices(name,starts_on,ends_on,adjustment_type,adjustment_value,operation,minimum_stay,active,weekdays,room_codes,rate_plan_keys,updated_at,created_at,owner_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12,$13) RETURNING id`,x.id?[x.name,x.startsOn,x.endsOn,x.adjustmentType,x.adjustmentValue,x.operation,x.minimumStay,x.active?1:0,JSON.stringify(x.weekdays),JSON.stringify(x.roomCodes),JSON.stringify(x.ratePlanKeys),now,u.ownerId,x.id]:[x.name,x.startsOn,x.endsOn,x.adjustmentType,x.adjustmentValue,x.operation,x.minimumStay,x.active?1:0,JSON.stringify(x.weekdays),JSON.stringify(x.roomCodes),JSON.stringify(x.ratePlanKeys),now,u.ownerId]);
 else result=await db().query(x.id?`UPDATE booking_restrictions SET name=$1,starts_on=$2,ends_on=$3,minimum_stay=$4,maximum_stay=$5,closed_arrival_weekdays=$6,closed_departure_weekdays=$7,room_codes=$8,rate_plan_keys=$9,active=$10,updated_at=$11 WHERE owner_id=$12 AND id=$13 RETURNING id`:`INSERT INTO booking_restrictions(name,starts_on,ends_on,minimum_stay,maximum_stay,closed_arrival_weekdays,closed_departure_weekdays,room_codes,rate_plan_keys,active,updated_at,created_at,owner_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11,$12) RETURNING id`,x.id?[x.name,x.startsOn,x.endsOn,x.minimumStay,x.maximumStay,JSON.stringify(x.closedArrivalWeekdays),JSON.stringify(x.closedDepartureWeekdays),JSON.stringify(x.roomCodes),JSON.stringify(x.ratePlanKeys),x.active?1:0,now,u.ownerId,x.id]:[x.name,x.startsOn,x.endsOn,x.minimumStay,x.maximumStay,JSON.stringify(x.closedArrivalWeekdays),JSON.stringify(x.closedDepartureWeekdays),JSON.stringify(x.roomCodes),JSON.stringify(x.ratePlanKeys),x.active?1:0,now,u.ownerId]);
 return Response.json({ok:Boolean(result.rowCount)},{status:result.rowCount?200:404})
 }catch(e){return Response.json({ok:false,error:e instanceof z.ZodError?"INVALID_INPUT":e instanceof Error?e.message:"SAVE_FAILED"},{status:e instanceof z.ZodError||e instanceof Error&&e.message==="INVALID_DATES"?400:500})}}
