export declare const events: readonly string[];
export declare const templateVariables: readonly string[];
export declare const PUBLIC_REVIEW_MIN_RATING: number;
export declare function greekTime(date: string, offsetDays: number, hour: number): number;
export declare function scheduleFor(event: string, booking: { check_in: string; check_out: string; created_at: number }, settings: { review_days_after_checkout: number; send_hour: number; checkin_days_before?: number; balance_days_before_checkout?: number; pre_arrival_days_before?: number; pre_arrival_hour?: number; welcome_hour?: number; pre_departure_hour?: number }): number;
export declare function interpolate(text: string, values: Record<string, string>): string;
export declare function athensToday(now: Date): string;
export declare function eligible(event: string, booking: { status: string; check_in: string; check_out: string; balance_cents: number; checkin_submitted?: boolean }, now: Date): boolean;
export declare function whatsappVariables(event: string, values: Record<string, string>): string[];
export declare function reviewRoute(rating: unknown): "public" | "private" | null;
export declare const triggeredEvents: string[];
export declare function guestMessaging(channel: unknown): boolean;
export declare function cancellationRefund(input: { paidCents: number; ratePolicy: unknown; cancellationDays: unknown; checkIn: string; cancelledOn: string; refundPercent?: unknown }): { outcome: "none_paid" | "refund" | "partial_refund" | "no_refund"; freeUntil: string | null; refundCents: number; percent: number };
export declare const cancellationReasons: string[];
export declare function reasonText(code: string, lang: string, custom?: string | null): string;
export declare function refundText(outcome: string, lang: string, extra?: { paid?: string; freeUntil?: string | null; nonRefundable?: boolean; refund?: string; percent?: number }): string;
export declare const triggeredTemplates: Record<"payment_failed" | "cancellation", Record<"el" | "en" | "fr" | "de" | "it" | "es", { subject: string; body: string }>>;
