import {z} from "zod";
import {requireApiUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {assertTrustedOrigin} from "@/lib/security/origin";
import {can} from "@/lib/security/permissions";
import {bookingLanguages} from "@/lib/booking-i18n";
const config={rooms:{table:"room_categories",permission:"rooms.edit",description:true},plans:{table:"rate_plans",permission:"pricing.edit",description:false},extras:{table:"extras",permission:"rooms.edit",description:true},charges:{table:"mandatory_charges",permission:"pricing.edit",description:false}} as const;
const translations=z.record(z.enum(bookingLanguages),z.string().trim().max(2000));
const input=z.object({kind:z.enum(["rooms","plans","extras","charges"]),id:z.number().int().positive(),names:translations,descriptions:translations.optional()});
export async function GET(){const u=await requireApiUser("dashboard.read");if(u instanceof Response)return u;const data:Record<string,unknown[]>={};for(const [kind,option] of Object.entries(config)){if(!can(u.role,option.permission as "rooms.edit"|"pricing.edit",u.permissions))continue;const names=kind==="rooms"?"COALESCE(name_en,name_el,'')":kind==="plans"?"name":kind==="extras"?"COALESCE(name_en,name_el,name)":"COALESCE(name_en,name_el,name)";const rows=await db().query(`SELECT id,${names} AS base_name,name_translations_json${option.description?",description_translations_json":""} FROM ${option.table} WHERE owner_id=$1 ORDER BY id`,[u.ownerId]);data[kind]=rows.rows}return Response.json({ok:true,data})}
export async function POST(request:Request){const u=await requireApiUser("dashboard.read");if(u instanceof Response)return u;try{assertTrustedOrigin(request);const value=input.parse(await request.json()),option=config[value.kind];if(!can(u.role,option.permission as "rooms.edit"|"pricing.edit",u.permissions))return Response.json({ok:false,error:"FORBIDDEN"},{status:403});const fields=option.description?"name_translations_json=$1,description_translations_json=$2":"name_translations_json=$1";const parameters=option.description?[JSON.stringify(value.names),JSON.stringify(value.descriptions??{}),u.ownerId,value.id]:[JSON.stringify(value.names),u.ownerId,value.id];const result=await db().query(`UPDATE ${option.table} SET ${fields} WHERE owner_id=$${option.description?3:2} AND id=$${option.description?4:3} RETURNING id`,parameters);return Response.json({ok:!!result.rowCount},{status:result.rowCount?200:404})}catch(e){return Response.json({ok:false,error:e instanceof z.ZodError?"INVALID_INPUT":"SAVE_FAILED"},{status:e instanceof z.ZodError?400:500})}}
