import {z} from "zod";
import {requireApiUser} from "@/lib/auth";
import {db,withTransaction} from "@/lib/db";
import {assertTrustedOrigin} from "@/lib/security/origin";
import {hashPassword} from "@/lib/security/password";
import {permissionKeys} from "@/lib/security/permissions";

const role=z.enum(["admin","reception","housekeeping","readonly"]);
const permissions=z.partialRecord(z.enum(permissionKeys),z.boolean());
const create=z.object({username:z.string().trim().min(3).max(40).regex(/^[a-zA-Z0-9._-]+$/),displayName:z.string().trim().min(2).max(100),email:z.email(),role,password:z.string().min(12).max(128),permissions:permissions.default({})});
const update=z.object({id:z.number().int().positive(),displayName:z.string().trim().min(2).max(100).optional(),email:z.email().optional(),role:role.optional(),active:z.boolean().optional(),password:z.string().min(12).max(128).optional(),permissions:permissions.optional()});
const list=`SELECT id,username,display_name,email,role,active,permissions_json FROM pms_staff_users WHERE owner_id=$1`;
export async function GET(){const u=await requireApiUser("users.manage");if(u instanceof Response)return u;const r=await db().query(`${list} ORDER BY display_name`,[u.ownerId]);return Response.json({ok:true,users:r.rows})}
export async function POST(request:Request){const u=await requireApiUser("users.manage");if(u instanceof Response)return u;try{assertTrustedOrigin(request);const i=create.parse(await request.json()),now=Date.now(),password=await hashPassword(i.password);const r=await withTransaction(async c=>{const created=await c.query(`INSERT INTO pms_staff_users(owner_id,username,display_name,email,password_hash,totp_secret,role,permissions_json,active,created_at,updated_at) VALUES($1,$2,$3,$4,$5,'',$6,$7,1,$8,$8) RETURNING id,username,display_name,email,role,active,permissions_json`,[u.ownerId,i.username,i.displayName,i.email,password,i.role,JSON.stringify(i.permissions),now]);await c.query(`INSERT INTO pms_user_audit(owner_id,actor_id,target_user_id,action,changes_json,created_at) VALUES($1,$2,$3,$4,$5,$6)`,[u.ownerId,u.id,created.rows[0].id,"create",JSON.stringify({role:i.role,active:true,permissions:i.permissions}),now]);return created});return Response.json({ok:true,user:r.rows[0]},{status:201})}catch(e){return Response.json({ok:false,error:e instanceof z.ZodError?"INVALID_INPUT":"CREATE_FAILED"},{status:400})}}
export async function PATCH(request:Request){const u=await requireApiUser("users.manage");if(u instanceof Response)return u;try{assertTrustedOrigin(request);const i=update.parse(await request.json());if(i.id===u.id&&(i.active===false||i.role!==undefined||i.permissions!==undefined))return Response.json({ok:false,error:"CANNOT_CHANGE_OWN_ACCESS"},{status:400});const updated=await withTransaction(async c=>{const current=await c.query(`${list} AND id=$2 FOR UPDATE`,[u.ownerId,i.id]);if(!current.rowCount)throw Error("NOT_FOUND");const row=current.rows[0];if(row.role==="owner"&&u.role!=="owner")throw Error("OWNER_PROTECTED");const hash=i.password?await hashPassword(i.password):undefined;const now=Date.now();const r=await c.query(`UPDATE pms_staff_users SET display_name=$1,email=$2,role=$3,active=$4,permissions_json=$5,password_hash=COALESCE($6,password_hash),updated_at=$7 WHERE owner_id=$8 AND id=$9 RETURNING id,username,display_name,email,role,active,permissions_json`,[i.displayName??row.display_name,i.email??row.email,i.role??row.role,i.active===undefined?row.active:i.active?1:0,i.permissions===undefined?row.permissions_json:JSON.stringify(i.permissions),hash??null,now,u.ownerId,i.id]);if(hash||i.role!==undefined||i.permissions!==undefined||i.active===false)await c.query(`UPDATE pms_sessions SET revoked_at=$1 WHERE owner_id=$2 AND staff_user_id=$3 AND revoked_at IS NULL`,[now,u.ownerId,i.id]);await c.query(`INSERT INTO pms_user_audit(owner_id,actor_id,target_user_id,action,changes_json,created_at) VALUES($1,$2,$3,$4,$5,$6)`,[u.ownerId,u.id,i.id,"update",JSON.stringify({displayNameChanged:i.displayName!==undefined,emailChanged:i.email!==undefined,role:i.role,active:i.active,permissions:i.permissions,passwordChanged:Boolean(hash)}),now]);return r.rows[0]});return Response.json({ok:true,user:updated})}catch(e){const m=e instanceof Error?e.message:"UPDATE_FAILED";return Response.json({ok:false,error:e instanceof z.ZodError?"INVALID_INPUT":m},{status:m==="NOT_FOUND"?404:400})}}
